### ISSUE TITLE
"404 not found" for images

### ISSUE THREAD

**Issue by LazarusX** [MicrosoftDocs/azure-docs.zh-cn#1]
Images referenced by articles ([example page](https://github.com/Microsoft/azure-docs.zh-cn/blob/master/includes/iot-hub-gateway-sdk-getstarted-selector.md)) in this repository are not found.

The images are supposed to be in the /includes/media directory, but that directory does not exist.

**Comment by SunnyDeng** [comment]
55393

**Comment by SunnyDeng** [comment]
@LazarusX this file get renamed, loc update caught up with the update at 8/23. Please let us know if you repro again.
