### ISSUE TITLE
Sign in return url

### ISSUE THREAD

**Issue by ivooQ** [MicrosoftDocs/azure-docs.zh-cn#100]
Nowhere in the document show me how to set the return URL after successfully signed in, however I found it in StackOverflow.
A sample is ~/.auth/login/aad?post_login_redirect_url=/welcome.html
Why the document doesn't tell me that?

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: d4518495-4e07-ce2e-4045-5a50b7922b55
* Version Independent ID: 034d1ba0-a737-21ab-3717-ed8798ac5fe1
* Content: [在 Azure 应用服务中自定义身份验证和授权](https://docs.microsoft.com/zh-cn/azure/app-service/app-service-authentication-how-to#configure-multiple-sign-in-options)
* Content Source: [articles/app-service/app-service-authentication-how-to.md](https://github.com/MicrosoftDocs/azure-docs.zh-cn/blob/live/articles/app-service/app-service-authentication-how-to.md)
* Service: **app-service**
* GitHub Login: @cephalin
* Microsoft Alias: **cephalin**

**Comment by cephalin** [comment]
@ivooQ Thank you for the feedback! I've updated the documentation and the live English page will be updated in a few hours. However the Chinese page update will be delayed.

#please-close
