### ISSUE TITLE
I want to add more synchronization settings.

### ISSUE THREAD

**Issue by gitYu1** [MicrosoftDocs/azure-docs.zh-cn#101]
如：1用户桌面图标布局(包括用户安装的软件)；
这是个大头，目前中国很多手机品牌都能同步以安装软件，换手机可以直接恢复上次同步的所有内容包括软件。
2用户开机启动项设置；
以上都可以增强用户体验。
祝微软越做越好！

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4459a0c8-0451-bbdf-3d2f-f62f46dc2240
* Version Independent ID: 7ebbbee6-1bd2-de5a-aabf-978d12099f3f
* Content: [Windows 10 漫游设置参考](https://docs.microsoft.com/zh-cn/azure/active-directory/active-directory-windows-enterprise-state-roaming-windows-settings-reference)
* Content Source: [articles/active-directory/active-directory-windows-enterprise-state-roaming-windows-settings-reference.md](https://github.com/MicrosoftDocs/azure-docs.zh-cn/blob/live/articles/active-directory/active-directory-windows-enterprise-state-roaming-windows-settings-reference.md)
* Service: **active-directory**
* GitHub Login: @MarkusVi
* Microsoft Alias: **markvi**

**Comment by LisandroSu** [comment]
你好，@gitYu1

非常感谢你的参与。我们的团队只能回应与文档相关的反馈。
 
请使用 DOCS 页面底部的“提供产品反馈”按钮记录你的产品反馈。

若有与文档相关的任何反馈，欢迎通过此通道将它记录下来。
 
非常感谢你对我们的文章作出的贡献。

深深的祝福，
Microsoft DOCS International   Team
