### ISSUE TITLE
java demo

### ISSUE THREAD

**Issue by weizhengduo** [MicrosoftDocs/azure-docs.zh-cn#103]
文本转语音（TTS）有没有java的demo,不知道如何把文本传给贵方

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: d6021ebc-4b2a-fbb3-84a4-1753b80442c3
* Version Independent ID: 4af2b683-7cc6-3aa4-eeb5-cf5a087094d1
* Content: [语音服务 REST API](https://docs.microsoft.com/zh-cn/azure/cognitive-services/speech-service/rest-apis#feedback)
* Content Source: [articles/cognitive-services/Speech-Service/rest-apis.md](https://github.com/MicrosoftDocs/azure-docs.zh-cn/blob/live/articles/cognitive-services/Speech-Service/rest-apis.md)
* Service: **cognitive-services**
* GitHub Login: @v-jerkin
* Microsoft Alias: **v-jerkin**

**Comment by LisandroSu** [comment]
你好，@weizhengduo

非常感谢你的参与。我们的团队只能回应与文档相关的反馈。 

请使用 DOCS 页面底部的“提供产品反馈”按钮记录你的产品反馈。 

若有与文档相关的任何反馈，欢迎通过此通道将它记录下来。 

非常感谢你对我们的文章作出的贡献。  

深深的祝福， 
Microsoft DOCS International Team
