### ISSUE TITLE
apim

### ISSUE THREAD

**Issue by dickh** [MicrosoftDocs/azure-docs.zh-cn#106]
[在此处输入反馈]

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 63549934-727b-06e9-9905-399791899d14
* Version Independent ID: d1dd5d59-5943-092e-2d77-0c8cf911873f
* Content: [使用 PowerShell 创建 Azure API 管理实例](https://docs.microsoft.com/zh-cn/azure/api-management/powershell-create-service-instance)
* Content Source: [articles/api-management/powershell-create-service-instance.md](https://github.com/MicrosoftDocs/azure-docs.zh-cn/blob/live/articles/api-management/powershell-create-service-instance.md)
* Service: **api-management**
* GitHub Login: @vladvino
* Microsoft Alias: **apimpm**

**Comment by LisandroSu** [comment]
您好, @dickh 

谢谢您的反馈。我们需要更多信息才能处理这个问题；您能否提供更加详细的说明？

深深的祝福， 
Microsoft DOCS International Team

**Comment by LisandroSu** [comment]
您好, @dickh

谢谢您的反馈。我们需要更多信息才能处理这个问题；您能否提供更加详细的说明？

深深的祝福， 
Microsoft DOCS International Team

**Comment by dickh** [comment]
我忘了我的问题是什么了

**Comment by LisandroSu** [comment]
@dickh  您好：

再次感謝您的寶貴意見。

很遺憾至今我們仍未收到您的進一步資訊，所以無法處理您的意見反應。目前我們會先將此 GitHub 問題結案處理，期望您日後能夠再提供更多的意見。

順頌時祺
Microsoft DOCS International Team
