### ISSUE TITLE
'pick host name from backend address' and 'host name's usage 

### ISSUE THREAD

**Issue by jasonwangnanjing** [MicrosoftDocs/azure-docs.zh-cn#110]
Hi AZURE
May you please explain in detail what is the influence of  option 'pick host name from backend address'? in case my backend IP is 10.240.0.33, will this be taked as host name?
What is the influence of the input field 'host name'? for example, if i input 'www.sina.com', will this be used as hostname?

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 5c7b8bcd-b263-692e-6d14-1663cdedef03
* Version Independent ID: f2307954-8544-d820-cb76-f7fa0a9601db
* Content: [通过 Azure 应用程序网关保护 Web 应用 - PowerShell](https://docs.microsoft.com/zh-cn/azure/application-gateway/application-gateway-web-app-powershell)
* Content Source: [articles/application-gateway/application-gateway-web-app-powershell.md](https://github.com/MicrosoftDocs/azure-docs.zh-cn/blob/live/articles/application-gateway/application-gateway-web-app-powershell.md)
* Service: **application-gateway**
* GitHub Login: @vhorne
* Microsoft Alias: **victorh**

**Comment by LisandroSu** [comment]
Hello, @jasonwangnanjing 

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
