### ISSUE TITLE
Excel ML add-in on Mac OS

### ISSUE THREAD

**Issue by HaoHoo** [MicrosoftDocs/azure-docs.zh-cn#111]
It's possible to support Excel for Mac OS?

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 5f7164d8-9388-4a96-aeb9-7a6ae813277f
* Version Independent ID: 3286af9d-821a-6202-638d-2a5e8d426b46
* Content: [机器学习 Web 服务的 Excel 外接程序](https://docs.microsoft.com/zh-cn/azure/machine-learning/studio/excel-add-in-for-web-services)
* Content Source: [articles/machine-learning/studio/excel-add-in-for-web-services.md](https://github.com/MicrosoftDocs/azure-docs.zh-cn/blob/live/articles/machine-learning/studio/excel-add-in-for-web-services.md)
* Service: **machine-learning**
* GitHub Login: @YasinMSFT
* Microsoft Alias: **yahajiza**

**Comment by LisandroSu** [comment]
Hello, @HaoHoo ,

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
