### ISSUE TITLE
关于P2S VPN 如何下发 自定义路由到客户端

### ISSUE THREAD

**Issue by chaiyuxiao** [MicrosoftDocs/azure-docs.zh-cn#112]
我想自定义几条路由，并且通过client连接到VPN网关之后，VPN网关下发到client修改client的本地路由表，这个功能可以实现吗？

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 59e72010-dab4-54d9-1409-c95b0ce60824
* Version Independent ID: 0da5450c-6181-1c27-93c0-b0c698d2d598
* Content: [使用点到站点和本机 Azure 证书身份验证将计算机连接到 Azure 虚拟网络：Azure 门户](https://docs.microsoft.com/zh-cn/azure/vpn-gateway/vpn-gateway-howto-point-to-site-resource-manager-portal)
* Content Source: [articles/vpn-gateway/vpn-gateway-howto-point-to-site-resource-manager-portal.md](https://github.com/MicrosoftDocs/azure-docs.zh-cn/blob/live/articles/vpn-gateway/vpn-gateway-howto-point-to-site-resource-manager-portal.md)
* Service: **vpn-gateway**
* GitHub Login: @cherylmc
* Microsoft Alias: **cherylmc**

**Comment by LisandroSu** [comment]
你好，@chaiyuxiao

非常感谢你的参与。我们的团队只能回应与文档相关的反馈。 

请使用 DOCS 页面底部的“提供产品反馈”按钮记录你的产品反馈。 

若有与文档相关的任何反馈，欢迎通过此通道将它记录下来。 

非常感谢你对我们的文章作出的贡献。  

深深的祝福， 
Microsoft DOCS International Team
