### ISSUE TITLE
can't open these links

### ISSUE THREAD

**Issue by SimpleLonely** [MicrosoftDocs/azure-docs.zh-cn#125]
https://github.com/Microsoft/botbuilder-tools/tree/master/Dispatch 
and #active-learning and so on. wish it to be fixed soon. thank you

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 902be7bb-e623-ff49-9d9d-e53f17161f06
* Version Independent ID: be07779d-229f-5ce4-5ea3-ae1497f650c7
* Content: [什么是语言理解 (LUIS) - Azure 认知服务](https://docs.microsoft.com/zh-cn/azure/cognitive-services/luis/what-is-luis#patterns)
* Content Source: [articles/cognitive-services/LUIS/what-is-luis.md](https://github.com/MicrosoftDocs/azure-docs.zh-cn/blob/live/articles/cognitive-services/LUIS/what-is-luis.md)
* Service: **cognitive-services**
* GitHub Login: @diberry
* Microsoft Alias: **diberry**

**Comment by LisandroSu** [comment]
Hello, @SimpleLonely ,
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Thank you for your feedback.
 
Our engineer team reviewed your suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/zh-cn/azure/cognitive-services/luis/what-is-luis#patterns. 

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Thank you for your feedback.
 
Our engineer team reviewed your suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/zh-cn/azure/cognitive-services/luis/what-is-luis#patterns. 

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.

Kind regards,
Microsoft DOCS International Team

**Comment by SimpleLonely** [comment]
Thank you!
