### ISSUE TITLE
Some error text

### ISSUE THREAD

**Issue by baron-zhang-avepoint** [MicrosoftDocs/azure-docs.zh-cn#128]
如果没有网络规则匹配项，并且数据包协议是 HTTP/HTTPS，则不会按应用程序规则评估数据包。

这句应该是错了

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 6392b4a0-fa1e-fe5e-a31b-1eee48b860ef
* Version Independent ID: 551028da-b651-30ac-0e77-9ee5eebf6bb0
* Content: [Azure 防火墙规则处理逻辑](https://docs.microsoft.com/zh-cn/azure/firewall/rule-processing)
* Content Source: [articles/firewall/rule-processing.md](https://github.com/MicrosoftDocs/azure-docs.zh-cn/blob/live/articles/firewall/rule-processing.md)
* Service: **firewall**
* GitHub Login: @vhorne
* Microsoft Alias: **victorh**

**Comment by LisandroSu** [comment]
你好，@baron-zhang-avepoint
 
感谢你的反馈。 
 
我们正在积极查看你的评论，并会很快地再次和你取得联系。 
 
深深的祝福， 
Microsoft DOCS International Team

**Comment by LisandroSu** [comment]
你好，@baron-zhang-avepoint
 
感谢你的反馈。 
 
我们正在积极查看你的评论，并会很快地再次和你取得联系。 
 
深深的祝福， 
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
你好，@baron-zhang-avepoint

感谢你的反馈。 

我们语言专家团队已评审并接受你的语言相关建议。我们已实施你的反馈，并将更新后的文章发布到 Docs 站点上的以下页面：XXX。  

非常感谢你对我们的文章作出的贡献，欢迎继续提供宝贵的反馈。 


深深的祝福，
