### ISSUE TITLE
这篇文章误导了我一星期的学习时间

### ISSUE THREAD

**Issue by waynebaby** [MicrosoftDocs/azure-docs.zh-cn#137]
这篇文章误导了我一星期的学习时间
因为
1 本机调试的时候iis express 或者asp.net core 进程必须用 azure 订阅账号权限登陆，所以我用公司账号的机器连接 msid 的azure账号试用了一辈子不成功 死的心都有
2 根本没告诉用户需要在 IAM 里面设置app service 的权限 所以你的app service连不上
3 根本没告诉用户 deploy的时候要在deploy profile里面加上 add a key vault.

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: ead83747-c629-e979-f0c5-5e4ba7eab154
* Version Independent ID: 792525b0-b7ad-aa7b-5425-cbd9dcfc3844
* Content: [使用 Visual Studio 将 Key Vault 支持添加到 ASP.NET 项目](https://docs.microsoft.com/zh-cn/azure/key-vault/vs-key-vault-add-connected-service)
* Content Source: [articles/key-vault/vs-key-vault-add-connected-service.md](https://github.com/MicrosoftDocs/azure-docs.zh-cn/blob/live/articles/key-vault/vs-key-vault-add-connected-service.md)
* Product: **visual-studio-dev15**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by LisandroSu** [comment]
Issue moved to [MicrosoftDocs/azure-docs #16503](https://github.com/MicrosoftDocs/azure-docs/issues/16503) via [**ZenHub**](https://www.zenhub.com/)

**Comment by LisandroSu** [comment]
你好，@waynebaby

非常感谢你的参与。你的反馈与原始文档有关。 

因此，我们会将此问题迁移到英文版存储库。请在这里查看问题的状态 - https://github.com/MicrosoftDocs/azure-docs/issues/16503。 

非常感谢你对我们的文章作出的贡献。  


深深的祝福， 
Microsoft DOCS International Team
