### ISSUE TITLE
what is the AccountName in the $connectionString?

### ISSUE THREAD

**Issue by panrar** [MicrosoftDocs/azure-docs.zh-cn#138]
$connectionString = "DefaultEndpointsProtocol=[http|https];AccountName=[yourAccount];AccountKey=[yourKey]"

I do not know what the accountName should be, can not find a way to fill it correctly. it seems accountname is a host, because any string be filled, for exam "xyz",  then exception will be: "Couldn't resolve host xyz.table.core.windows.net", what is it? 

please give a real example, thanks.

 

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 3ec7ea93-cf7d-ca3a-10d3-7a13a6f356ba
* Version Independent ID: 23d86ac7-06ac-6ac0-97dd-cc06c9f3ef74
* Content: [如何通过 PHP 使用 Azure 存储表服务或 Azure Cosmos DB 表 API](https://docs.microsoft.com/zh-cn/azure/cosmos-db/table-storage-how-to-use-php#update-an-entity)
* Content Source: [articles/cosmos-db/table-storage-how-to-use-php.md](https://github.com/MicrosoftDocs/azure-docs.zh-cn/blob/live/articles/cosmos-db/table-storage-how-to-use-php.md)
* Service: **cosmos-db**
* GitHub Login: @SnehaGunda
* Microsoft Alias: **sngun**

**Comment by LisandroSu** [comment]
Hello, @panrar ,

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
