### ISSUE TITLE
Duplicate characters " * "

### ISSUE THREAD

**Issue by awong1900** [MicrosoftDocs/azure-docs.zh-cn#14]
```
使用 HTTP 发送设备到云的消息时，属性名称和值只能包含 ASCII 字母数字字符加上 {'!', '#', '$', '%, '&', "'", '*', '*', '+', '-', '.', '^', '_', '`', '|', '~'}。
```

**Comment by SunnyDeng** [comment]
@awong1900 thank you for the contribution! Could you point me the article URL?

**Comment by awong1900** [comment]
https://docs.microsoft.com/zh-cn/azure/iot-hub/iot-hub-devguide-messages-construct

```
在执行以下操作时，属性名称和值只能包含 ASCII 字母数字字符加上 {'!', '#', '$', '%, '&', "'", '*', '*', '+', '-', '.', '^', '_', '`', '|', '~'}：
```

**Comment by SunnyDeng** [comment]
@awong1900 while i am contacting with the writer, could you please tell whether you are using global Chinese version or Mooncake version? 
@dominicbetts

**Comment by dominicbetts** [comment]
@SunnyDeng - the "*" is unnecessarily duplicated - I'll update my version. Thanks

**Comment by SunnyDeng** [comment]
Thanks @dominicbetts !
@awong1900  zh-cn fix is done, close this PR.
