### ISSUE TITLE
where is the translator server's endpoint

### ISSUE THREAD

**Issue by SongKeTong** [MicrosoftDocs/azure-docs.zh-cn#145]
where is the translator server's endpoint and protocol

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: fec5b265-9ada-269a-f955-d84e4b90c4bc
* Version Independent ID: 11493d93-8c5f-4ce7-9a27-0d46ae10d1f3
* Content: [排查语音服务 SDK 问题 - Azure Cognitive Services](https://docs.microsoft.com/zh-cn/azure/cognitive-services/speech-service/troubleshooting#feedback)
* Content Source: [articles/cognitive-services/Speech-Service/troubleshooting.md](https://github.com/MicrosoftDocs/azure-docs.zh-cn/blob/live/articles/cognitive-services/Speech-Service/troubleshooting.md)
* Service: **cognitive-services**
* GitHub Login: @wolfma61
* Microsoft Alias: **wolfma**

**Comment by LisandroSu** [comment]
Hello, @SongKeTong 

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
