### ISSUE TITLE
部署模块找不到

### ISSUE THREAD

**Issue by yilo2417** [MicrosoftDocs/azure-docs.zh-cn#146]
部署模块部分
第四步 在“添加模块”步骤的“部署模块”部分，单击“添加”，然后选择“IoT Edge 模块”。
找不到 部署模块部分，建议加一些截图。或者将云平台里的相应英文都翻译成中文，如果云平台里是因为，建议文档里也在中文后加上英文，以便定位和确认。

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: e2289383-6ce2-a036-c710-7d1fad6e1700
* Version Independent ID: 3b902941-0876-17c3-3f0b-a4b7f7770531
* Content: [快速入门 Azure IoT Edge + Linux](https://docs.microsoft.com/zh-cn/azure/iot-edge/quickstart-linux#deploy-a-module)
* Content Source: [articles/iot-edge/quickstart-linux.md](https://github.com/MicrosoftDocs/azure-docs.zh-cn/blob/live/articles/iot-edge/quickstart-linux.md)
* Service: **iot-edge**
* GitHub Login: @kgremban
* Microsoft Alias: **kgremban**

**Comment by CeciAc** [comment]
你好，@yilo2417
 
感谢你的反馈。 
 
我们正在积极查看你的评论，并会很快地再次和你取得联系。 
 
深深的祝福， 
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #18716](https://github.com/MicrosoftDocs/azure-docs/issues/18716) via [**ZenHub**](https://www.zenhub.com/)
