### ISSUE TITLE
运行之后状态返回500

### ISSUE THREAD

**Issue by yatyu** [MicrosoftDocs/azure-docs.zh-cn#148]
我按照这个文档的过程一步步操作后得到的状态是"500 Internal Server Error"我不清楚具体是哪里出了问题，但是我很肯定我是按照这个文档来做的。

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 939101cd-9c92-ed8f-b241-664794db8a0d
* Version Independent ID: 21392fd3-c4e7-f785-a660-ebbbf88646e4
* Content: [使用 Azure Cosmos DB 和 Azure Functions 存储非结构化数据](https://docs.microsoft.com/zh-cn/azure/azure-functions/functions-integrate-store-unstructured-data-cosmosdb?tabs=csharp)
* Content Source: [articles/azure-functions/functions-integrate-store-unstructured-data-cosmosdb.md](https://github.com/MicrosoftDocs/azure-docs.zh-cn/blob/live/articles/azure-functions/functions-integrate-store-unstructured-data-cosmosdb.md)
* Service: **azure-functions**
* GitHub Login: @ggailey777
* Microsoft Alias: **glenga**

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #19166](https://github.com/MicrosoftDocs/azure-docs/issues/19166) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
你好，@yatyu

非常感谢你的参与。你的反馈与原始文档有关。 

因此，我们会将此问题迁移到英文版存储库。请在这里查看问题的状态 - https://github.com/MicrosoftDocs/azure-docs/issues/19166。 

非常感谢你对我们的文章作出的贡献。  


深深的祝福， 
Microsoft DOCS International Team
