### ISSUE TITLE
what's difference between Azure Front Door and Traffic Manager?

### ISSUE THREAD

**Issue by keithcn** [MicrosoftDocs/azure-docs.zh-cn#149]
same as title.

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: dbadca96-7341-36d0-8a38-1c6a5c96b22d
* Version Independent ID: 2fad91dc-25f8-0c7a-c21d-93986ec51145
* Content: [Azure Front Door Service](https://docs.microsoft.com/zh-cn/azure/frontdoor/front-door-overview)
* Content Source: [articles/frontdoor/front-door-overview.md](https://github.com/MicrosoftDocs/azure-docs.zh-cn/blob/live/articles/frontdoor/front-door-overview.md)
* Service: **frontdoor**
* GitHub Login: @sharad4u
* Microsoft Alias: **sharadag**

**Comment by CeciAc** [comment]
Hello, @keithcn

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
