### ISSUE TITLE
赞

### ISSUE THREAD

**Issue by CherryTT** [MicrosoftDocs/azure-docs.zh-cn#155]
[在此处输入反馈]

内容很清晰
---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 65a16702-87ad-4801-5171-f5e629661cb4
* Version Independent ID: bdd076dd-9b65-4054-b7f8-16e12e6a6f99
* Content: [导入 BACPAC 文件以创建 Azure SQL 数据库](https://docs.microsoft.com/zh-cn/azure/sql-database/sql-database-import)
* Content Source: [articles/sql-database/sql-database-import.md](https://github.com/MicrosoftDocs/azure-docs.zh-cn/blob/live/articles/sql-database/sql-database-import.md)
* Service: **sql-database**
* GitHub Login: @CarlRabeler
* Microsoft Alias: **carlrab**

**Comment by CeciAc** [comment]
你好，@CherryTT 

非常感谢你提供反馈。很高兴我们的文档满足你的期望。 
欢迎提供宝贵的反馈，以便我们继续改进体验。 


深深的祝福， 
Microsoft DOCS International Team
