### ISSUE TITLE
使用该开发团队示例报错问题

### ISSUE THREAD

**Issue by zh1a1baby** [MicrosoftDocs/azure-docs.zh-cn#166]
[在此处输入反馈]

NSMutableArray* categories = [[NSMutableArray alloc] init];

if (self.WorldSwitch.isOn) [categories addObject:@"World"];
if (self.PoliticsSwitch.isOn) [categories addObject:@"Politics"];
if (self.BusinessSwitch.isOn) [categories addObject:@"Business"];
if (self.TechnologySwitch.isOn) [categories addObject:@"Technology"];
if (self.ScienceSwitch.isOn) [categories addObject:@"Science"];
if (self.SportsSwitch.isOn) [categories addObject:@"Sports"];

Notifications* notifications = [(AppDelegate*)[[UIApplication sharedApplication]delegate] notifications];

[notifications storeCategoriesAndSubscribeWithCategories:categories completion: ^(NSError* error) {
    if (!error) {
        [(AppDelegate*)[[UIApplication sharedApplication]delegate] MessageBox:@"Notification" message:@"Subscribed!"];
    } else {
        NSLog(@"Error subscribing: %@", error);
    }
}];
此段代码报错应该如何解决

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 4e30d710-7de5-4043-47e4-2e18706a39de
* Version Independent ID: 4b0d4868-b374-0ca7-f807-3bee87d3de98
* Content: [使用 Azure 通知中心向特定 iOS 设备推送通知](https://docs.microsoft.com/zh-cn/azure/notification-hubs/notification-hubs-ios-xplat-segmented-apns-push-notification)
* Content Source: [articles/notification-hubs/notification-hubs-ios-xplat-segmented-apns-push-notification.md](https://github.com/MicrosoftDocs/azure-docs.zh-cn/blob/live/articles/notification-hubs/notification-hubs-ios-xplat-segmented-apns-push-notification.md)
* Service: **notification-hubs**
* GitHub Login: @dimazaid
* Microsoft Alias: **dimazaid**

**Comment by CeciAc** [comment]
你好，@zh1a1baby 

非常感谢你的参与。我们的团队只能回应与文档相关的反馈。 

请使用 DOCS 页面底部的“提供产品反馈”按钮记录你的产品反馈。 

若有与文档相关的任何反馈，欢迎通过此通道将它记录下来。 

非常感谢你对我们的文章作出的贡献。  

深深的祝福， 
Microsoft DOCS International Team
