### ISSUE TITLE
中文本地化问题

### ISSUE THREAD

**Issue by rayind** [MicrosoftDocs/azure-docs.zh-cn#167]
”文本到语音转换“一节中的”服务名称映射“一列不应翻译成中文，包括标点

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 4de08d1f-8114-7bef-7ef4-022f79c69742
* Version Independent ID: 4c0ceab9-24ed-de01-db30-31acf1de0f48
* Content: [语言支持 - 语音服务 API - Azure Cognitive Services](https://docs.microsoft.com/zh-cn/azure/cognitive-services/speech-service/language-support)
* Content Source: [articles/cognitive-services/Speech-Service/language-support.md](https://github.com/MicrosoftDocs/azure-docs.zh-cn/blob/live/articles/cognitive-services/Speech-Service/language-support.md)
* Service: **cognitive-services**
* GitHub Login: @erhopf
* Microsoft Alias: **erhopf**

**Comment by CeciAc** [comment]
你好，@rayind
 
感谢你的反馈。 
 
我们正在积极查看你的评论，并会很快地再次和你取得联系。 
 
深深的祝福， 
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
你好，@rayind
 
感谢你的反馈。 
 
我们正在积极查看你的评论，并会很快地再次和你取得联系。 
 
深深的祝福， 
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
你好，@rayind

感谢你的反馈。 

我们语言专家团队已评审并接受你的语言相关建议。我们已实施你的反馈，并将更新后的文章发布到 Docs 站点上的以下页面：https://docs.microsoft.com/zh-cn/azure/cognitive-services/speech-service/language-support。  

非常感谢你对我们的文章作出的贡献，欢迎继续提供宝贵的反馈。 


深深的祝福， 

Microsoft DOCS International Team
