### ISSUE TITLE
免费订阅Data Transfer Out计费

### ISSUE THREAD

**Issue by zhuimei123** [MicrosoftDocs/azure-docs.zh-cn#238]
我的免费订阅Data Transfer Out发生了很大的计费，请问这是正常的吗？我觉得应该不正常，我应该没有这样的费用。

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 29ee8475-1a56-48d8-ab6e-624029b979b1
* Version Independent ID: 412b20dd-c2b9-f1c3-b8c6-f7fc056ea0b6
* Content: [监视和跟踪 Azure 免费服务的使用情况](https://docs.microsoft.com/zh-cn/azure/billing/billing-check-free-service-usage)
* Content Source: [articles/billing/billing-check-free-service-usage.md](https://github.com/MicrosoftDocs/azure-docs.zh-cn/blob/live/articles/billing/billing-check-free-service-usage.md)
* Service: **billing**
* GitHub Login: @amberbhargava
* Microsoft Alias: **cwatson**

**Comment by CeciAc** [comment]
你好，@zhuimei123

非常感谢你的参与。我们的团队只能回应与文档相关的反馈。 

请使用 DOCS 页面底部的“提供产品反馈”按钮记录你的产品反馈。 

若有与文档相关的任何反馈，欢迎通过此通道将它记录下来。 

非常感谢你对我们的文章作出的贡献。  

深深的祝福， 
Microsoft DOCS International Team
