### ISSUE TITLE
create_blob_from_stream

### ISSUE THREAD

**Issue by 15106119704** [MicrosoftDocs/azure-docs.zh-cn#245]
create_blob_from_stream？？？where？？

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 15591874-317e-ce4c-0dff-20d06b625e40
* Version Independent ID: be7fed9a-343a-0ec7-a94d-02c354d1ae33
* Content: [Azure 快速入门 - 使用 Python 在对象存储中创建 Blob](https://docs.microsoft.com/zh-cn/azure/storage/blobs/storage-quickstart-blobs-python)
* Content Source: [articles/storage/blobs/storage-quickstart-blobs-python.md](https://github.com/MicrosoftDocs/azure-docs.zh-cn/blob/live/articles/storage/blobs/storage-quickstart-blobs-python.md)
* Service: **storage**
* GitHub Login: @tamram
* Microsoft Alias: **tamram**

**Comment by LisandroSu** [comment]
Hello, @15106119704 
 
We truly appreciate your comment and we strive to improve your experience in docs.microsoft.com. However, we need more information in order be able to address your feedback. Can you please provide more detailed information and clarify your comment?
 
Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @15106119704 
 
Thanks once again for your comment.
Unfortunately, we are still missing information and we are unable to process your feedback. We are closing this GitHub issue at this time but we encourage you to submit more feedback in the future.

Kind regards,
Microsoft DOCS International Team
