### ISSUE TITLE
关于向谷歌推送url连接

### ISSUE THREAD

**Issue by wuzinong** [MicrosoftDocs/azure-docs.zh-cn#28]
Hi 您好，
     感谢提供这么有帮助的示例，在做消息推送的时候遇到一个问题，想请教一下。关于如何使用notification hub 向使用google服务的设备推送可使用网页打开的消息。
     比如使用baidu服务的时候可以推送一个json，包含open_type，设置它为1，并且传递一个url，那么当设备接收到这消息的时候会打开对应url的网页，但是我看了下没有找到google的相对应的功能，我想问下google是否也有对应的功能。感谢

**Comment by SunnyDeng** [comment]
@wuzinong thanks for the contribution here! Are you asking how to use MS Notification Hub in google Chrome? Please refer to https://channel9.msdn.com/Shows/Azure-Friday/Using-Azure-Notification-Hubs-for-Push-Notifications-in-Google-Chrome.
