### ISSUE TITLE
cortana prebuilt apps intents and entities need update

### ISSUE THREAD

**Issue by quxian** [MicrosoftDocs/azure-docs.zh-cn#30]
There are  many intents and entities that needs to be updated in [Cortana prebuild apps](https://github.com/Microsoft/azure-docs/blob/master/articles/cognitive-services/LUIS/Cortana-Prebuilt-App.md).

**Comment by SunnyDeng** [comment]
@quxian Thank for the contribution to zh-cn Azure tech doc. The article was updated. 
Hope the article is helpful to you.
