### ISSUE TITLE
w

### ISSUE THREAD

**Issue by wikenZ** [MicrosoftDocs/azure-docs.zh-cn#309]
wok

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 3ab24f5b-50fd-37cc-e031-34301147953d
* Version Independent ID: c2bc2467-8743-491c-c84c-f6983772f4da
* Content: [教程 - 使用 Azure CLI 管理 Azure 磁盘](https://docs.microsoft.com/zh-cn/azure/virtual-machines/linux/tutorial-manage-disks)
* Content Source: [articles/virtual-machines/linux/tutorial-manage-disks.md](https://github.com/MicrosoftDocs/azure-docs.zh-cn/blob/live/articles/virtual-machines/linux/tutorial-manage-disks.md)
* Service: **virtual-machines-linux**
* GitHub Login: @cynthn
* Microsoft Alias: **cynthn**

**Comment by CeciAc** [comment]
No actionable feedback.
