### ISSUE TITLE
Cortana prebuilt apps 文档该更新了

### ISSUE THREAD

**Issue by quxian** [MicrosoftDocs/azure-docs.zh-cn#31]
经过测试发现，Cortana prebuilt apps有好多的实体需要更新，旧的文档缺少好多实体介绍，请问什么时候更新？

**Comment by quxian** [comment]
忘了说了，[这个文档](https://github.com/Microsoft/azure-docs/blob/master/articles/cognitive-services/LUIS/Cortana-Prebuilt-App.md)

**Comment by SunnyDeng** [comment]
@DeniseMak quxian requested to update the article related with 'Cortana prebuilt apps'. He would like to see the entity introduction. The article is https://github.com/MicrosoftDocs/azure-docs/blob/master/articles/cognitive-services/LUIS/Cortana-Prebuilt-App.md. 
"Tests found that Cortana prebuilt apps there are many entities need to be updated, the old document is missing a lot of entities introduced, what time the update?" -- Bing MT

**Comment by DeniseMak** [comment]
Hi Sunny – Thank you for your feedback. We have a work item to track this, and can update you on the ETA when we triage the work. I can send you a link to some entity information offline in case you are blocked on the missing information.

-Denise

**Comment by SunnyDeng** [comment]
The articles were updated. Close this one.
