### ISSUE TITLE
https://docs.microsoft.com/zh-cn/azure/cosmos-db/create-table-dotnet  Use wrong picture

### ISSUE THREAD

**Issue by wingfeng** [MicrosoftDocs/azure-docs.zh-cn#32]
中文版的Cosmos数据库文档，用错了DocumentDB的截图了。

**Comment by SunnyDeng** [comment]
@wingfeng Thanks for the contribution to the zh-cn tech doc. The doc was updated back to jun 14th and we are continuously updating. Hope the article will help you!
