### ISSUE TITLE
using （zh-CN，Yaoyao，Apollo） faild

### ISSUE THREAD

**Issue by tanjianpublic** [MicrosoftDocs/azure-docs.zh-cn#332]
Request :
&lt;speak version='1.0' xmlns='http://www.w3.org/2001/10/synthesis' xml:lang='en-US'&gt;&lt;voice name='Microsoft Server Speech Text to Speech Voice (zh-CN, Yaoyao,Apollo)'&gt;&lt;prosody rate="+30.00%"&gt;语音转文字测试&lt;/prosody&gt;&lt;/voice&gt;&lt;/speak&gt;

Response :
Response status code does not indicate success: 400 (Unsupported voice Microsoft Server Speech Text to Speech Voice (zh-CN, Yaoyao,Apollo).).”

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 4de08d1f-8114-7bef-7ef4-022f79c69742
* Version Independent ID: 4c0ceab9-24ed-de01-db30-31acf1de0f48
* Content: [语言支持 - 语音服务 API - Azure Cognitive Services](https://docs.microsoft.com/zh-cn/azure/cognitive-services/speech-service/language-support)
* Content Source: [articles/cognitive-services/Speech-Service/language-support.md](https://github.com/MicrosoftDocs/azure-docs.zh-cn/blob/live/articles/cognitive-services/Speech-Service/language-support.md)
* Service: **cognitive-services**
* GitHub Login: @erhopf
* Microsoft Alias: **erhopf**

**Comment by CeciAc** [comment]
你好，@tanjianpublic

非常感谢你的参与。我们的团队只能回应与文档相关的反馈。 

请使用 DOCS 页面底部的“提供产品反馈”按钮记录你的产品反馈。 

若有与文档相关的任何反馈，欢迎通过此通道将它记录下来。 

非常感谢你对我们的文章作出的贡献。  

深深的祝福， 
Microsoft DOCS International Team
