### ISSUE TITLE
标记为notranslate, 多加了空格，bug反馈

### ISSUE THREAD

**Issue by fresh7849** [MicrosoftDocs/azure-docs.zh-cn#346]
标记为notranslate的标签，内容有时会被无辜的前后加个空格。
例如英文翻译成俄语
翻译内容: ‘you are welcome <span class="notranslate">Jerry</span>’
结果: ’Пожалуйста<span class="notranslate">Jerry</span>‘
当在后面加个空格时：
翻译内容: 'you are welcome <span class="notranslate">Jerry</span> '
结果: 'Вы радушны <span class="notranslate"> Jerry </span>'
‘Jerry’字符串前后多加了空格。
标记内容不应该保持不变吗？

测试时的相关参数：
api url:https://api.cognitive.microsofttranslator.com/translate
'api-version': '3.0',
'to':'ru',
'profanityAction':'Marked',
'profanityMarker':'Asterisk',
'textType':'html'

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: e605b68f-9ada-9ca5-dfbc-ae23d54795f7
* Version Independent ID: 344bd19f-0f63-7a17-8b17-1342faa0fc1b
* Content: [阻止翻译内容 - 文本翻译 API](https://docs.microsoft.com/zh-cn/azure/cognitive-services/translator/prevent-translation)
* Content Source: [articles/cognitive-services/Translator/prevent-translation.md](https://github.com/MicrosoftDocs/azure-docs.zh-cn/blob/live/articles/cognitive-services/Translator/prevent-translation.md)
* Service: **cognitive-services**
* GitHub Login: @Jann-Skotdal
* Microsoft Alias: **v-jansko**

**Comment by CeciAc** [comment]
你好，@fresh7849
非常感谢你的参与。我们的团队只能回应与文档相关的反馈。 

请使用 DOCS 页面底部的“提供产品反馈”按钮记录你的产品反馈。 

若有与文档相关的任何反馈，欢迎通过此通道将它记录下来。 

非常感谢你对我们的文章作出的贡献。  

深深的祝福， 
Microsoft DOCS International Team
