### ISSUE TITLE
请问我是否在两台iPhone上同时使用Authenticator？

### ISSUE THREAD

**Issue by batugao** [MicrosoftDocs/azure-docs.zh-cn#348]
我随身常备两台iPhone使用，请问是否可以同时安装Authenticator然后使用我的双重验证？

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: b6b484b7-f909-4f26-0a08-4cafcc229c4d
* Version Independent ID: bf50d85e-78c0-0b7a-05db-69a949cb5e96
* Content: [有关 Microsoft Authenticator 应用的帮助 - Azure Active Directory](https://docs.microsoft.com/zh-cn/azure/active-directory/user-help/microsoft-authenticator-app-faq)
* Content Source: [articles/active-directory/user-help/microsoft-authenticator-app-faq.md](https://github.com/MicrosoftDocs/azure-docs.zh-cn/blob/live/articles/active-directory/user-help/microsoft-authenticator-app-faq.md)
* Service: **active-directory**
* GitHub Login: @eross-msft
* Microsoft Alias: **lizross**

**Comment by CeciAc** [comment]
你好，@batugao
非常感谢你的参与。我们的团队只能回应与文档相关的反馈。 

请使用 DOCS 页面底部的“提供产品反馈”按钮记录你的产品反馈。 

若有与文档相关的任何反馈，欢迎通过此通道将它记录下来。 

非常感谢你对我们的文章作出的贡献。  

深深的祝福， 
Microsoft DOCS International Team
