### ISSUE TITLE
13698427777@163.com

### ISSUE THREAD

**Issue by 13698427777** [MicrosoftDocs/azure-docs.zh-cn#360]
[在此处输入反馈]13698427777@163.com

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: c8ed6cf5-c042-76ef-1030-769f87972d93
* Version Independent ID: 8d284ce0-1185-1770-0b17-503cd63660ac
* Content: [设置安全信息以使用安全性问题 - Azure Active Directory](https://docs.microsoft.com/zh-cn/azure/active-directory/user-help/security-info-setup-questions)
* Content Source: [articles/active-directory/user-help/security-info-setup-questions.md](https://github.com/MicrosoftDocs/azure-docs.zh-cn/blob/live/articles/active-directory/user-help/security-info-setup-questions.md)
* Service: **active-directory**
* GitHub Login: @eross-msft
* Microsoft Alias: **lizross**

**Comment by LisandroSu** [comment]
你好，@13698427777

我们诚挚感谢你的评论，我们会努力改善你在 docs.microsoft.com 的使用体验。但是，为了解决你的反馈，我们需要更多信息。你可以提供更为详细的信息并阐明你的评论吗？

顺祝商祺！
Microsoft DOCS 国际团队

**Comment by CeciAc** [comment]
你好，@13698427777
我们正在跟进我们之前的评论。为了解决你的反馈，我们需要更多信息。你可以提供更为详细的信息并阐明你的评论吗？
顺祝商祺！
Microsoft DOCS 国际团队

**Comment by CeciAc** [comment]
你好，@13698427777
再次感谢你的评论。
很遗憾，我们仍然缺少信息，无法处理你的反馈。我们当前将关闭此 GitHub 问题，但我们欢迎你在以后提交更多反馈。
顺祝商祺！
Microsoft DOCS 国际团队
