### ISSUE TITLE
Some documents have been forgotten to translate into Chinese

### ISSUE THREAD

**Issue by saraao** [MicrosoftDocs/azure-docs.zh-cn#362]
文档中Set up your development environment被部分被漏翻译

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 65ca3600-cbad-b9eb-3c7e-22b5251226ec
* Version Independent ID: 8881b6f3-c64d-f758-15c8-79e10e9764a9
* Content: [回归模型教程：准备数据 - Azure Machine Learning service](https://docs.microsoft.com/zh-cn/azure/machine-learning/service/tutorial-data-prep)
* Content Source: [articles/machine-learning/service/tutorial-data-prep.md](https://github.com/MicrosoftDocs/azure-docs.zh-cn/blob/live/articles/machine-learning/service/tutorial-data-prep.md)
* Service: **machine-learning**
* GitHub Login: @cforbe
* Microsoft Alias: **cforbe**

**Comment by CeciAc** [comment]
你好，@saraao
 
感谢你的反馈。 
 
我们正在积极查看你的评论，并会很快地再次和你取得联系。 
 
深深的祝福， 
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #25980](https://github.com/MicrosoftDocs/azure-docs/issues/25980) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
你好，@saraao

非常感谢你的参与。你的反馈与原始文档有关。 

因此，我们会将此问题迁移到英文版存储库。请在这里查看问题的状态 - https://github.com/MicrosoftDocs/azure-docs/issues/25980

非常感谢你对我们的文章作出的贡献。  


深深的祝福， 
Microsoft DOCS International Team
