### ISSUE TITLE
未知步骤 "Train a local model" appear in Azure notebooks

### ISSUE THREAD

**Issue by saraao** [MicrosoftDocs/azure-docs.zh-cn#363]
根据以上教程打开Azure notebooks的 Getting started&gt;tutorials&gt;img-classification-part1-training.ipynb中，未知步骤"Train a local model"出现在步骤“Upload data to the cloud”与“Train on a remote cluster”之间，与说明文档顺序不符。且在逐步运行时，“"Train a local model"中的代码无法正常运行。必须跳过Train a local model直接运行Train on a remote cluster部分才能正常运行。
备注：该未知步骤只出现在Azure notebooks的教程中。在说明文档和GitHub的教程中无该步骤。

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 4bee4b9a-ce0f-f98b-3160-d6c4a40ef3ac
* Version Independent ID: a0475a9e-47f6-2803-8707-fac54ba898dd
* Content: [图像分类教程：训练模型 - Azure Machine Learning service](https://docs.microsoft.com/zh-cn/azure/machine-learning/service/tutorial-train-models-with-aml)
* Content Source: [articles/machine-learning/service/tutorial-train-models-with-aml.md](https://github.com/MicrosoftDocs/azure-docs.zh-cn/blob/live/articles/machine-learning/service/tutorial-train-models-with-aml.md)
* Service: **machine-learning**
* GitHub Login: @hning86
* Microsoft Alias: **haining**

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #25939](https://github.com/MicrosoftDocs/azure-docs/issues/25939) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
你好，@
saraao

非常感谢你的参与。你的反馈与原始文档有关。 

因此，我们会将此问题迁移到英文版存储库。请在这里查看问题的状态 - https://github.com/MicrosoftDocs/azure-docs/issues/25939

非常感谢你对我们的文章作出的贡献。  


深深的祝福， 
Microsoft DOCS International Team
