### ISSUE TITLE
step“打开笔记本”有疑惑

### ISSUE THREAD

**Issue by saraao** [MicrosoftDocs/azure-docs.zh-cn#365]
第一次阅读时无法理解“工作区页”是什么。可否截图更大些并指出哪里是工作区页部分（像视频中那样截图，或像英文版网页https://docs.microsoft.com/en-us/azure/machine-learning/service/quickstart-get-started那样截图）。

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 5ae9c8cf-5f68-9baa-1660-118208034381
* Version Independent ID: 48d350ca-0ef8-3500-57ae-a5ec6c36ac79
* Content: [通过 Azure 门户快速入门 - Azure Machine Learning service](https://docs.microsoft.com/zh-cn/azure/machine-learning/service/quickstart-get-started)
* Content Source: [articles/machine-learning/service/quickstart-get-started.md](https://github.com/MicrosoftDocs/azure-docs.zh-cn/blob/live/articles/machine-learning/service/quickstart-get-started.md)
* Service: **machine-learning**
* GitHub Login: @hning86
* Microsoft Alias: **haining**

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #25945](https://github.com/MicrosoftDocs/azure-docs/issues/25945) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
你好，@saraao

非常感谢你的参与。你的反馈与原始文档有关。 

因此，我们会将此问题迁移到英文版存储库。请在这里查看问题的状态 - https://github.com/MicrosoftDocs/azure-docs/issues/25945

非常感谢你对我们的文章作出的贡献。  


深深的祝福， 
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
你好，@saraao
 
感谢你的反馈。 
 
我们正在积极查看你的评论，并会很快地再次和你取得联系。 
 
深深的祝福， 
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
你好，@saraao

感谢你的反馈。 

我们的工程团队已评审并接受你的建议。我们已实施你的反馈，并将更新后的文章发布到 Docs 站点上的以下页面：https://docs.microsoft.com/zh-cn/azure/machine-learning/service/quickstart-get-started

非常感谢你对我们的文章作出的贡献，欢迎继续提供宝贵的反馈。 

深深的祝福， 
Microsoft DOCS International Team
