### ISSUE TITLE
建议添加Azure门户-机器学习服务工作区-应用程序的介绍噢

### ISSUE THREAD

**Issue by saraao** [MicrosoftDocs/azure-docs.zh-cn#369]
建议添加Azure门户-机器学习服务工作区-应用程序的介绍噢。
比如：
试验 - 这些是我们训练和测试模型的地方。我们用一个试验来尝试解决一个问题，或者针对一个机器学习算法来创建一个试验。
管道 - 管道用于创建和管理将机器学习阶段拼接在一起的工作流。包括数据准备、模型训练、模型部署和推断等各种机器学习阶段。
计算 - 这些是在Azure中训练我们的模型的计算目标。
模型 - 我们训练模型的输出文件。
图像 - 包含我们模型的打包/容器化版本的容器映像，可供部署。
部署 - 我们部署的模型，在Azure Container Instances上， Azure Kubernetes Service cluster，FPGA上或Azure IoT Edge上无服务器运行。
活动 - 我们在Workspace中所做的工作的概述。

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 5ae9c8cf-5f68-9baa-1660-118208034381
* Version Independent ID: 48d350ca-0ef8-3500-57ae-a5ec6c36ac79
* Content: [通过 Azure 门户快速入门 - Azure Machine Learning service](https://docs.microsoft.com/zh-cn/azure/machine-learning/service/quickstart-get-started)
* Content Source: [articles/machine-learning/service/quickstart-get-started.md](https://github.com/MicrosoftDocs/azure-docs.zh-cn/blob/live/articles/machine-learning/service/quickstart-get-started.md)
* Service: **machine-learning**
* GitHub Login: @hning86
* Microsoft Alias: **haining**

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #25947](https://github.com/MicrosoftDocs/azure-docs/issues/25947) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
你好，@saraao

非常感谢你的参与。你的反馈与原始文档有关。 

因此，我们会将此问题迁移到英文版存储库。请在这里查看问题的状态 - https://github.com/MicrosoftDocs/azure-docs/issues/25947

非常感谢你对我们的文章作出的贡献。  


深深的祝福， 
Microsoft DOCS International Team
