### ISSUE TITLE
如何用Azure机器学习服务建立模型并投入生产

### ISSUE THREAD

**Issue by saraao** [MicrosoftDocs/azure-docs.zh-cn#370]
这也许有助于用户理解：
从拥有数据到将机器学习模型投入生产，对于Azure机器学习来说是一个非常直接的过程。总的来说，它只包含几个步骤：
1.将数据导入系统或使数据可访问
2.为您的模型编写代码，任何支持的框架（pytorch、tensorflow、scikit-learn等）
3.在Azure Batch AI、DSVM（数据科学虚拟机）、Kubernetes（通过Azure Kubernetes Service）或本地训练您的模型
4.Azure Machine Learning会将模型输出的开发存储在Blob存储中
5.对于这些开发，我们将让Azure Machine Learning通过使用Score.py脚本加载模型并对传入的数据进行推论/评分，从而构建一个容器化的模型。
6.Azure Machine Learning会将容器映像推送到Azure容器注册表中
7.在那里，我们可以让Azure Machine Learning将它们部署到
Azure Container Instances
Azure Kubernetes Service
FPGAs
Azure IoT Edge
8.Application Insights已连接，因此我们可以获得用于监控模型的操作指标

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 570174c0-ec43-ab79-2d1d-38903cb35df5
* Version Independent ID: 01a073f1-ad36-835a-b090-f0b2b3a7cabe
* Content: [什么是 - Azure Machine Learning service](https://docs.microsoft.com/zh-cn/azure/machine-learning/service/overview-what-is-azure-ml)
* Content Source: [articles/machine-learning/service/overview-what-is-azure-ml.md](https://github.com/MicrosoftDocs/azure-docs.zh-cn/blob/live/articles/machine-learning/service/overview-what-is-azure-ml.md)
* Service: **machine-learning**
* GitHub Login: @garyericson
* Microsoft Alias: **garye**

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #25946](https://github.com/MicrosoftDocs/azure-docs/issues/25946) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
你好，@saraao

非常感谢你的参与。你的反馈与原始文档有关。 

因此，我们会将此问题迁移到英文版存储库。请在这里查看问题的状态 - https://github.com/MicrosoftDocs/azure-docs/issues/25946

非常感谢你对我们的文章作出的贡献。  


深深的祝福， 
Microsoft DOCS International Team
