### ISSUE TITLE
what is the “racyScore” means here？	

### ISSUE THREAD

**Issue by saraao** [MicrosoftDocs/azure-docs.zh-cn#371]
Chinese document use 猥亵(which means indecent behaviour) to translate the racy score, is it right?

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: a34ab04c-3e27-0b10-d067-7ec728fc24bd
* Version Independent ID: e698c7db-11d7-6354-496a-ffa3bef9148e
* Content: [探讨 v2 API 生成的视频索引器输出](https://docs.microsoft.com/zh-cn/azure/media-services/video-indexer/video-indexer-output-json-v2)
* Content Source: [articles/media-services/video-indexer/video-indexer-output-json-v2.md](https://github.com/MicrosoftDocs/azure-docs.zh-cn/blob/live/articles/media-services/video-indexer/video-indexer-output-json-v2.md)
* Service: **media-services**
* GitHub Login: @Juliako
* Microsoft Alias: **juliako**

**Comment by yanchenpek** [comment]
I think “不雅” could be better than "猥亵”.

**Comment by CeciAc** [comment]
Hello, @
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @saraao 
 
Thank you for your feedback.
 
Our linguistic team reviewed your linguist suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/zh-cn/azure/media-services/video-indexer/video-indexer-output-json-v2

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.
	
Kind regards,
Microsoft DOCS International Team
