### ISSUE TITLE
videoId is dynamic type

### ISSUE THREAD

**Issue by saraao** [MicrosoftDocs/azure-docs.zh-cn#372]
when I run the part:
// get the video id from the upload result
var videoId = JsonConvert.DeserializeObject&lt;dynamic&gt;(uploadResult)["id"];
Debug.WriteLine("Uploaded");
Debug.WriteLine("Video ID: " + videoId);   
It gives me a RuntimeBinderException like this: 
Additional information: Cannot dynamically invoke method 'WriteLine' because it has a Conditional attribute.

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 079621d5-cf9b-3a9c-c1ed-77e29e43b2be
* Version Independent ID: a8e46e38-c7e4-5f47-b306-482f2e2f30fb
* Content: [使用视频索引器 API - Azure](https://docs.microsoft.com/zh-cn/azure/media-services/video-indexer/video-indexer-use-apis)
* Content Source: [articles/media-services/video-indexer/video-indexer-use-apis.md](https://github.com/MicrosoftDocs/azure-docs.zh-cn/blob/live/articles/media-services/video-indexer/video-indexer-use-apis.md)
* Service: **media-services**
* GitHub Login: @Juliako
* Microsoft Alias: **juliako**

**Comment by CeciAc** [comment]
Hello, @saraao 

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
