### ISSUE TITLE
Translattion issue

### ISSUE THREAD

**Issue by newbe36524** [MicrosoftDocs/azure-docs.zh-cn#373]
There is no need to translate Stackoverflow to "堆栈溢出". we all know that is a BBS.

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 015f6f83-a6be-c2e8-773f-5220ec8ca41a
* Version Independent ID: b962bde9-c513-ced9-6c91-013fc0c2baf5
* Content: [什么是 Azure SQL 数据仓库？](https://docs.microsoft.com/zh-cn/azure/sql-data-warehouse/sql-data-warehouse-overview-what-is#feedback)
* Content Source: [articles/sql-data-warehouse/sql-data-warehouse-overview-what-is.md](https://github.com/MicrosoftDocs/azure-docs.zh-cn/blob/live/articles/sql-data-warehouse/sql-data-warehouse-overview-what-is.md)
* Service: **sql-data-warehouse**
* GitHub Login: @igorstanko
* Microsoft Alias: **igorstan**

**Comment by CeciAc** [comment]
Hello, @newbe36524 
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @newbe36524 
 
Thank you for your feedback.
 
Our linguistic team reviewed your linguist suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/zh-cn/azure/sql-data-warehouse/sql-data-warehouse-overview-what-is#feedback

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.
	
Kind regards,
Microsoft DOCS International Team
