### ISSUE TITLE
sudo 密码

### ISSUE THREAD

**Issue by xueyanfeng** [MicrosoftDocs/azure-docs.zh-cn#374]
您好，输入sudo之后，对应的输入密码是什么呢？

**Comment by CeciAc** [comment]
你好，@xueyanfeng
我们诚挚感谢你的评论，我们会努力改善你在 docs.microsoft.com 的使用体验。但是，为了解决你的反馈，我们需要更多信息。你可以提供更为详细的信息并阐明你的评论吗？
顺祝商祺！
Microsoft DOCS 国际团队

**Comment by xueyanfeng** [comment]
![image](https://user-images.githubusercontent.com/24717634/54202681-892e9900-450b-11e9-88ee-d869fd7d4ec5.png)

就是运行程序时，需要安装gensim python库，安装时，
![image](https://user-images.githubusercontent.com/24717634/54202767-b4b18380-450b-11e9-871a-c1c10e37a7d8.png)

输入sudo 时，需要输入密码，但输入账号密码显示密码不对，我想咨询这个密码哪儿看呢，或者是输入哪个密码呢，谢谢您的回复。

**Comment by CeciAc** [comment]
你好，@
非常感谢你的参与。我们的团队只能回应与文档相关的反馈。 

Provide product feedback here: https://feedback.azure.com/forums/34192--general-feedback

若有与文档相关的任何反馈，欢迎通过此通道将它记录下来。 

非常感谢你对我们的文章作出的贡献。  

深深的祝福， 
Microsoft DOCS International Team
