### ISSUE TITLE
Running module error

### ISSUE THREAD

**Issue by cuntoulishifu** [MicrosoftDocs/azure-docs.zh-cn#378]
According to the documentation I got the following error message：

Exception has occurred: CLR/System.AggregateException
An unhandled exception of type 'System.AggregateException' occurred in System.Private.CoreLib.dll: 'One or more errors occurred.'
 Inner exceptions found, see $exception in variables window for more details.
 Innermost exception 	 System.InvalidOperationException : Environment variable IOTEDGE_WORKLOADURI is required.
   at Microsoft.Azure.Devices.Client.Edge.EdgeModuleClientFactory.&lt;CreateInternalClientFromEnvironmentAsync&gt;d__16.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at SampleModuleVSCODE.Program.&lt;Init&gt;d__12.MoveNext() in E:\code\bo-iotmodule\EdgeSolutionvscode\modules\SampleModuleVSCODE\Program.cs:line 144

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 181d5562-f8d7-9c59-85ea-09efbe397f3e
* Version Independent ID: dbedd952-a050-286e-c951-4529ec8e87b8
* Content: [教程：创建自定义 C# 模块 - Azure IoT Edge](https://docs.microsoft.com/zh-cn/azure/iot-edge/tutorial-csharp-module#feedback)
* Content Source: [articles/iot-edge/tutorial-csharp-module.md](https://github.com/MicrosoftDocs/azure-docs.zh-cn/blob/live/articles/iot-edge/tutorial-csharp-module.md)
* Service: **iot-edge**
* GitHub Login: @kgremban
* Microsoft Alias: **kgremban**

**Comment by CeciAc** [comment]
Hello, @cuntoulishifu 

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
