### ISSUE TITLE
表格数据错误

### ISSUE THREAD

**Issue by Kucashu** [MicrosoftDocs/azure-docs.zh-cn#382]
NVv2 系列（预览版）表格中 Standard_NV6s_v2 的GPU数为 “第”。
---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: c946c151-c1a6-59bc-2e44-6a820547f48e
* Version Independent ID: 572ed0c0-8c4d-3629-044d-c7a34c8281a6
* Content: [Azure Linux VM 大小 - GPU](https://docs.microsoft.com/zh-cn/azure/virtual-machines/linux/sizes-gpu#feedback)
* Content Source: [articles/virtual-machines/linux/sizes-gpu.md](https://github.com/MicrosoftDocs/azure-docs.zh-cn/blob/live/articles/virtual-machines/linux/sizes-gpu.md)
* Service: **virtual-machines-linux**
* GitHub Login: @jonbeck7
* Microsoft Alias: **jonbeck**

**Comment by CeciAc** [comment]
Hello, @Kucashu 
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by Kucashu** [comment]
Thanks

**Comment by CeciAc** [comment]
Hello, @Kucashu 
 
Thank you for your feedback.
 
Our linguistic team reviewed your linguist suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/zh-cn/azure/virtual-machines/linux/sizes-gpu#feedback

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.
	
Kind regards,
Microsoft DOCS International Team
