### ISSUE TITLE
nodejs上载文件名包含中文时报错

### ISSUE THREAD

**Issue by MoonKing123** [MicrosoftDocs/azure-docs.zh-cn#390]
本地上载和流上载均报错: Error: Request path contains unescaped characters

在Azure web portal上手动上传含中文名的文件没有问题

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: dae2738c-ba71-e828-ce61-7d6ae66b06aa
* Version Independent ID: ace95080-b838-40e3-2fcd-fce8da08e9de
* Content: [使用 Azure Storage v10 SDK for JavaScript 上载、下载、列出和删除 blob](https://docs.microsoft.com/zh-cn/azure/storage/blobs/storage-quickstart-blobs-nodejs-v10#feedback)
* Content Source: [articles/storage/blobs/storage-quickstart-blobs-nodejs-v10.md](https://github.com/MicrosoftDocs/azure-docs.zh-cn/blob/live/articles/storage/blobs/storage-quickstart-blobs-nodejs-v10.md)
* Service: **storage**
* Sub-service: **blobs**
* GitHub Login: @tamram
* Microsoft Alias: **tamram**

**Comment by CeciAc** [comment]
你好，@MoonKing123
非常感谢你的参与。我们的团队只能回应与文档相关的反馈。 

请使用 DOCS 页面底部的“提供产品反馈”按钮记录你的产品反馈。 

若有与文档相关的任何反馈，欢迎通过此通道将它记录下来。 

非常感谢你对我们的文章作出的贡献。  

深深的祝福， 
Microsoft DOCS International Team
