### ISSUE TITLE
Why level 3 have less units? 

### ISSUE THREAD

**Issue by henwujun** [MicrosoftDocs/azure-docs.zh-cn#416]
"A level 1 or 2 IoT Hub instance can have as many as 200 units associated with it. A level 3 IoT Hub instance can have up to 10 units. " 

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 45b76f3e-0318-070e-ff9f-0598ed6379b1
* Version Independent ID: 52d8706b-30a2-93db-020c-1dc7098730f9
* Content: [Azure IoT 中心缩放](https://docs.microsoft.com/zh-cn/azure/iot-hub/iot-hub-scaling#feedback)
* Content Source: [articles/iot-hub/iot-hub-scaling.md](https://github.com/MicrosoftDocs/azure-docs.zh-cn/blob/master/articles/iot-hub/iot-hub-scaling.md)
* Service: **iot-hub**
* GitHub Login: @wesmc7777
* Microsoft Alias: **wesmc**

**Comment by CeciAc** [comment]
Hello, @henwujun

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
