### ISSUE TITLE
资源网页地址不对 ： https://<app_name>.scm.azurewebsites.net/ZipDeployUI

### ISSUE THREAD

**Issue by haohuancheng** [MicrosoftDocs/azure-docs.zh-cn#417]
我更换了 &lt;app_name&gt;后，这个地址还是不能访问。说 zipdeployui这个位置不对。前面地址可以访问。但不是可以提交zip的网页，所以无法继续学习提交网站zip文件。

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 4b0165d7-6462-842c-76ec-1a1f344fa51a
* Version Independent ID: 3b2c77ed-d9eb-cf20-0ace-908b88927e54
* Content: [创建 Node.js Web 应用 - Azure 应用服务](https://docs.microsoft.com/zh-cn/azure/app-service/app-service-web-get-started-nodejs#feedback)
* Content Source: [articles/app-service/app-service-web-get-started-nodejs.md](https://github.com/MicrosoftDocs/azure-docs.zh-cn/blob/master/articles/app-service/app-service-web-get-started-nodejs.md)
* Service: **app-service-web**
* GitHub Login: @cephalin
* Microsoft Alias: **cephalin**

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #30284](https://github.com/MicrosoftDocs/azure-docs/issues/30284) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #30285](https://github.com/MicrosoftDocs/azure-docs/issues/30285) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
你好，@haohuancheng

非常感谢你的参与。你的反馈与原始文档有关。 

因此，我们会将此问题迁移到英文版存储库。请在这里查看问题的状态 - https://github.com/MicrosoftDocs/azure-docs/issues/30285

非常感谢你对我们的文章作出的贡献。  


深深的祝福， 
Microsoft DOCS International Team
