### ISSUE TITLE
 process server 

### ISSUE THREAD

**Issue by xiaosawagziluqi** [MicrosoftDocs/azure-docs.zh-cn#427]
Is multiple process servers forming a cluster?

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 9f8b6d0d-22ec-65e3-c21f-6a40fd2f1787
* Version Independent ID: dc284d51-3502-b8f4-5eb6-1473a56b14ca
* Content: [使用 Azure Site Recovery 执行 VMware 到 Azure 灾难恢复的体系结构](https://docs.microsoft.com/zh-cn/azure/site-recovery/vmware-azure-architecture#feedback)
* Content Source: [articles/site-recovery/vmware-azure-architecture.md](https://github.com/MicrosoftDocs/azure-docs.zh-cn/blob/master/articles/site-recovery/vmware-azure-architecture.md)
* Service: **site-recovery**
* GitHub Login: @rayne-wiselman
* Microsoft Alias: **raynew**

**Comment by CeciAc** [comment]
Hello, @xiaosawagziluqi

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
