### ISSUE TITLE
利用rest api 接口方式获取资源更改报错

### ISSUE THREAD

**Issue by niutf** [MicrosoftDocs/azure-docs.zh-cn#442]
报错说明 无权在范围“/providers/Microsoft.ResourceGraph”内执行操作“Microsoft.ResourceGraph/resources/action”。"

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 733fcd9b-e234-8765-a7e0-498ded659ddc
* Version Independent ID: bd115a3e-37c9-66c9-da11-68b46b563275
* Content: [获取资源更改 - Azure Resource Graph](https://docs.microsoft.com/zh-cn/azure/governance/resource-graph/how-to/get-resource-changes#feedback)
* Content Source: [articles/governance/resource-graph/how-to/get-resource-changes.md](https://github.com/MicrosoftDocs/azure-docs.zh-cn/blob/master/articles/governance/resource-graph/how-to/get-resource-changes.md)
* Service: **resource-graph**
* GitHub Login: @DCtheGeek
* Microsoft Alias: **dacoulte**

**Comment by CeciAc** [comment]
你好，@niutf

非常感谢你的参与。我们的团队只能回应与文档相关的反馈。 

请使用 DOCS 页面底部的“提供产品反馈”按钮记录你的产品反馈。 

若有与文档相关的任何反馈，欢迎通过此通道将它记录下来。 

非常感谢你对我们的文章作出的贡献。  

深深的祝福， 
Microsoft DOCS International Team
