### ISSUE TITLE
Free trial version can only be used in English?

### ISSUE THREAD

**Issue by LiChangying** [MicrosoftDocs/azure-docs.zh-cn#484]
If not，which one parameter can change recognition language?

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: a0c01253-54e1-02da-e7f5-3be6bfbf2294
* Version Independent ID: 27dd48d8-d829-79ec-a5f8-b7dae2855aa1
* Content: [快速入门：识别语音，.NET Framework (Windows) - 语音服务 - Azure Cognitive Services](https://docs.microsoft.com/zh-cn/azure/cognitive-services/speech-service/quickstart-csharp-dotnet-windows)
* Content Source: [articles/cognitive-services/Speech-Service/quickstart-csharp-dotnet-windows.md](https://github.com/MicrosoftDocs/azure-docs.zh-cn/blob/master/articles/cognitive-services/Speech-Service/quickstart-csharp-dotnet-windows.md)
* Service: **cognitive-services**
* Sub-service: **speech-service**
* GitHub Login: @wolfma61
* Microsoft Alias: **wolfma**

**Comment by CeciAc** [comment]
Hello, @LiChangying 

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
