### ISSUE TITLE
what is the : subscriptionKey ?  my Subscription ID, or: the Manage keys:  Key1 and Key2?

### ISSUE THREAD

**Issue by haohuancheng** [MicrosoftDocs/azure-docs.zh-cn#488]
The all not work :-)

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: a1a5561a-e55e-276b-84a3-b3c643a1d03c
* Version Independent ID: 77ba94f1-57cd-9aca-7850-ae32704ce257
* Content: [快速入门：识别语音，Node.js - 语音服务 - Azure Cognitive Services](https://docs.microsoft.com/zh-cn/azure/cognitive-services/speech-service/quickstart-js-node#feedback)
* Content Source: [articles/cognitive-services/Speech-Service/quickstart-js-node.md](https://github.com/MicrosoftDocs/azure-docs.zh-cn/blob/master/articles/cognitive-services/Speech-Service/quickstart-js-node.md)
* Service: **cognitive-services**
* Sub-service: **speech-service**
* GitHub Login: @fmegen
* Microsoft Alias: **fmegen**

**Comment by haohuancheng** [comment]
Solved. The Region name must not have space char.

**Comment by CeciAc** [comment]
Hello, @haohuancheng 

Your feedback is much appreciated. We are glad to see that your experience with our documentation meets your expectations.
We encourage you to provide your valuable feedback so that we can continue improve your experience.

Kind regards,
Microsoft DOCS International Team
