### ISSUE TITLE
Where should I put these code in?

### ISSUE THREAD

**Issue by jznling** [MicrosoftDocs/azure-docs.zh-cn#532]
Thanks for the step-by-step tutorial. I understand what the code means, but don't know where I should put these in. Could you tell me the files I should work on?

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 5a5d261b-4f35-5a21-266c-cd916ec27645
* Version Independent ID: e09c9318-f7fa-ca76-6a0e-1c4d70c04a5f
* Content: [如何创建和使用 Azure，Java 中的空间定位点的定位点定位](https://docs.microsoft.com/zh-cn/azure/spatial-anchors/how-tos/create-locate-anchors-java)
* Content Source: [articles/spatial-anchors/how-tos/create-locate-anchors-java.md](https://github.com/MicrosoftDocs/azure-docs.zh-cn/blob/master/articles/spatial-anchors/how-tos/create-locate-anchors-java.md)
* Service: **azure-spatial-anchors**
* GitHub Login: @RamonArguelles
* Microsoft Alias: **rgarcia**

**Comment by CeciAc** [comment]
Hello, @jznling 

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
