### ISSUE TITLE
使用putty登录虚拟机时，登录失败

### ISSUE THREAD

**Issue by SuperCatss** [MicrosoftDocs/azure-docs.zh-cn#593]
当从azure 下载 id_rsa 文件时，文件格式默认是pem的 需要转换为ppk，才能使用putty登录虚拟机。
https://social.msdn.microsoft.com/Forums/en-US/129a6745-4368-4fb4-a391-620bcb9ee588/how-should-i-download-the-idrsapub-file-in-azure?forum=WAVirtualMachinesforWindows

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 814b92ed-f712-53c8-644b-d3be513a4d06
* Version Independent ID: 79d8998f-1b47-40ec-e975-8eeda383b0cf
* Content: [快速入门 - 在 Azure 门户中创建 Linux VM](https://docs.microsoft.com/zh-cn/azure/virtual-machines/linux/quick-create-portal#feedback)
* Content Source: [articles/virtual-machines/linux/quick-create-portal.md](https://github.com/MicrosoftDocs/azure-docs.zh-cn/blob/master/articles/virtual-machines/linux/quick-create-portal.md)
* Service: **virtual-machines-linux**
* GitHub Login: @cynthn
* Microsoft Alias: **cynthn**

**Comment by srvbpigh** [comment]
Hello, @SuperCatss
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
你好，@SuperCatss
非常感谢你的参与。我们的团队只能回应与文档相关的反馈。 

请使用 DOCS 页面底部的“提供产品反馈”按钮记录你的产品反馈。 

若有与文档相关的任何反馈，欢迎通过此通道将它记录下来。 

非常感谢你对我们的文章作出的贡献。  

深深的祝福， 
Microsoft DOCS International Team

**Comment by SuperCatss** [comment]
> 你好，@SuperCatss
> 非常感谢你的参与。我们的团队只能回应与文档相关的反馈。 
> 
> 请使用 DOCS 页面底部的“提供产品反馈”按钮记录你的产品反馈。 
> 
> 若有与文档相关的任何反馈，欢迎通过此通道将它记录下来。 
> 
> 非常感谢你对我们的文章作出的贡献。  
> 
> 深深的祝福， 
> Microsoft DOCS International Team

你好，在这篇文档中 [https://docs.microsoft.com/zh-cn/azure/virtual-machines/linux/ssh-from-windows](url)，我们将看到在ssh 与 windows 的配合使用以及putty的使用，但是我在创建虚拟机时，使用cloud shell 创建了 ssh。我希望在文档中，能有这种情况的使用教程，因为 cloud shell 创建的 id_rsa 私钥文件格式是不能直接在putty 中使用的。这是我提出这个issues的初衷。谢谢
