### ISSUE TITLE
Can't find firmware folder

### ISSUE THREAD

**Issue by ifsheldon** [MicrosoftDocs/azure-docs.zh-cn#597]
I've installed the SDK correctly and everything runs fine, but I can't find the firmware folder

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 36b7b2d0-f11a-4b73-3a9d-3032da7fd36f
* Version Independent ID: dd269642-3af1-ab93-de7a-f7171b17ee7b
* Content: [更新 Azure Kinect DK 固件](https://docs.microsoft.com/zh-cn/azure/Kinect-dk/update-device-firmware)
* Content Source: [articles/kinect-dk/update-device-firmware.md](https://github.com/MicrosoftDocs/azure-docs.zh-cn/blob/master/articles/kinect-dk/update-device-firmware.md)
* Product: **kinect-dk**
* GitHub Login: @tesych
* Microsoft Alias: **tesych**

**Comment by srvbpigh** [comment]
Hello, @ifsheldon
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @ifsheldon

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
