### ISSUE TITLE
Can the domian to be verified contain sub path?

### ISSUE THREAD

**Issue by Zhang-lujia** [MicrosoftDocs/azure-docs.zh-cn#600]
I try to verify the Publisher Domain of out app , which values is like "https://www.xxxx.cn/abc",  however the prompt says "Verification of publisher domain failed. Property publisherDomain has an invalid value. [B7jMt]". So I wonder whether the Pushiser Domian can't contain sub path, which means only domains like "https://www.xxx.cn"  are acceptable.

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 61edea45-b5d6-05b3-33c3-2265ef8cb309
* Version Independent ID: c7d5813c-5cf1-44c3-88ff-3c194d3e44ad
* Content: [配置应用程序的发布者域](https://docs.microsoft.com/zh-cn/azure/active-directory/develop/howto-configure-publisher-domain)
* Content Source: [articles/active-directory/develop/howto-configure-publisher-domain.md](https://github.com/MicrosoftDocs/azure-docs.zh-cn/blob/master/articles/active-directory/develop/howto-configure-publisher-domain.md)
* Service: **active-directory**
* Sub-service: **develop**
* GitHub Login: @rwike77
* Microsoft Alias: **ryanwi**

**Comment by srvbpigh** [comment]
Hello, @Zhang-lujia
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @Zhang-lujia

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
