### ISSUE TITLE
语速的调节参数

### ISSUE THREAD

**Issue by lang1019** [MicrosoftDocs/azure-docs.zh-cn#632]
有没语速的调节参数

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: e351e013-771a-bfdc-0f76-815316c7717d
* Version Independent ID: 8c3a1bbe-196a-13b8-f905-b8ea7bfd0e7a
* Content: [文本到语音 API 参考 (REST)-语音服务 - Azure Cognitive Services](https://docs.microsoft.com/zh-cn/azure/cognitive-services/speech-service/rest-text-to-speech#feedback)
* Content Source: [articles/cognitive-services/Speech-Service/rest-text-to-speech.md](https://github.com/MicrosoftDocs/azure-docs.zh-cn/blob/master/articles/cognitive-services/Speech-Service/rest-text-to-speech.md)
* Service: **cognitive-services**
* Sub-service: **speech-service**
* GitHub Login: @erhopf
* Microsoft Alias: **erhopf**

**Comment by srvbpigh** [comment]
Hello, @lang1019
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
你好，@lang1019
我们诚挚感谢你的评论，我们会努力改善你在 docs.microsoft.com 的使用体验。但是，为了解决你的反馈，我们需要更多信息。你可以提供更为详细的信息并阐明你的评论吗？
顺祝商祺！
Microsoft DOCS 国际团队

**Comment by lang1019** [comment]
关于文本转语音的rest api 的相关参数是否有关于语速调节的

**Comment by CeciAc** [comment]
你好，@lang1019
非常感谢你的参与。我们的团队只能回应与文档相关的反馈。 

请使用 DOCS 页面底部的“提供产品反馈”按钮记录你的产品反馈。 

若有与文档相关的任何反馈，欢迎通过此通道将它记录下来。 

非常感谢你对我们的文章作出的贡献。  

深深的祝福， 
Microsoft DOCS International Team
