### ISSUE TITLE
Translation Issue

### ISSUE THREAD

**Issue by v-tawe** [MicrosoftDocs/azure-docs.zh-cn#663]
Translate "recipe" as "食谱" seems not suitable here.

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 00c9a955-9d4f-d582-a637-e9f79905fe4f
* Version Independent ID: a169a399-e545-620a-7560-4360f4993c18
* Content: [Docker 容器的食谱 - Azure Cognitive Services](https://docs.microsoft.com/zh-cn/azure/cognitive-services/containers/container-reuse-recipe#feedback)
* Content Source: [articles/cognitive-services/containers/container-reuse-recipe.md](https://github.com/MicrosoftDocs/azure-docs.zh-cn/blob/master/articles/cognitive-services/containers/container-reuse-recipe.md)
* Service: **cognitive-services**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by srvbpigh** [comment]
Hello, @v-tawe
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @v-tawe
 
Thank you for your feedback.
 
Our linguistic team reviewed your linguist suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/zh-cn/azure/cognitive-services/containers/container-reuse-recipe#feedback

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.
	
Kind regards,
Microsoft DOCS International Team
