### ISSUE TITLE
Faq里翻译有误

### ISSUE THREAD

**Issue by virtualcca** [MicrosoftDocs/azure-docs.zh-cn#664]
https://docs.microsoft.com/zh-cn/azure/azure-cache-for-redis/cache-how-to-premium-clustering#do-all-redis-clients-support-clustering 章节里面第一行第二句“ StackExchange.Redis 是不支持该功能的客户端”翻译有误，应该要翻译为“ StackExchange.Redis 是支持该功能的客户端之一“

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 2fbf7b9e-ded8-3cd5-2615-6828ca4f8325
* Version Independent ID: d0a60bbe-b472-f362-bb67-3467b0ba900c
* Content: [如何为高级 Azure Redis 缓存配置 Redis 群集功能](https://docs.microsoft.com/zh-cn/azure/azure-cache-for-redis/cache-how-to-premium-clustering#do-all-redis-clients-support-clustering)
* Content Source: [articles/azure-cache-for-redis/cache-how-to-premium-clustering.md](https://github.com/MicrosoftDocs/azure-docs.zh-cn/blob/master/articles/azure-cache-for-redis/cache-how-to-premium-clustering.md)
* Service: **cache**
* GitHub Login: @yegu-ms
* Microsoft Alias: **yegu**

**Comment by srvbpigh** [comment]
Hello, @virtualcca
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
你好，@virtualcca  

感谢你的反馈。 

我们语言专家团队已评审并接受你的语言相关建议。我们已实施你的反馈，并将更新后的文章发布到 Docs 站点上的以下页面：https://docs.microsoft.com/zh-cn/azure/azure-cache-for-redis/cache-how-to-premium-clustering#do-all-redis-clients-support-clustering

非常感谢你对我们的文章作出的贡献，欢迎继续提供宝贵的反馈。 


深深的祝福， 

Microsoft DOCS International Team
