### ISSUE TITLE
main phone number and secondary phone number both changed and Authenticator app can't reach. 

### ISSUE THREAD

**Issue by YimingWang47** [MicrosoftDocs/azure-docs.zh-cn#667]
all I have is my password, how could I deal with it?
I'm a student and I am a user of school AAD. should I contact the administrator?

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 5a5d93c5-5135-b9e9-e536-eb0830918b2e
* Version Independent ID: 49be1539-737b-8874-eca6-1cdbc5263d73
* Content: [管理双因素验证设置-Azure Active Directory](https://docs.microsoft.com/zh-cn/azure/active-directory/user-help/multi-factor-authentication-end-user-manage-settings?source=docs#feedback)
* Content Source: [articles/active-directory/user-help/multi-factor-authentication-end-user-manage-settings.md](https://github.com/MicrosoftDocs/azure-docs.zh-cn/blob/master/articles/active-directory/user-help/multi-factor-authentication-end-user-manage-settings.md)
* Service: **active-directory**
* Sub-service: **user-help**
* GitHub Login: @eross-msft
* Microsoft Alias: **lizross**

**Comment by srvbpigh** [comment]
Hello, @YimingWang47
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @YimingWang47 

Your contribution is much appreciated. Yet, this feedback is related with product, please kindly log by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles.
	
Kind regards,
Microsoft DOCS International Team
