### ISSUE TITLE
识别出错

### ISSUE THREAD

**Issue by 876278378** [MicrosoftDocs/azure-docs.zh-cn#668]
AudioRecord: start() status -38  如何处理

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 26b5a45a-6fa7-f898-fcf5-781210fbee9e
* Version Independent ID: 90ff521b-37f5-38a1-ace0-6ad5989b6dab
* Content: [快速入门：在 Android 上运行语音设备 SDK - 语音服务 - Azure Cognitive Services](https://docs.microsoft.com/zh-cn/azure/cognitive-services/Speech-Service/speech-devices-sdk-android-quickstart#run-the-sample-application)
* Content Source: [articles/cognitive-services/Speech-Service/speech-devices-sdk-android-quickstart.md](https://github.com/MicrosoftDocs/azure-docs.zh-cn/blob/master/articles/cognitive-services/Speech-Service/speech-devices-sdk-android-quickstart.md)
* Service: **cognitive-services**
* Sub-service: **speech-service**
* GitHub Login: @erhopf
* Microsoft Alias: **erhopf**

**Comment by srvbpigh** [comment]
Hello, @876278378
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
你好，@876278378 

非常感谢你的参与。我们的团队只能回应与文档相关的反馈。 

请使用 DOCS 页面底部的“提供产品反馈”按钮记录你的产品反馈。 

若有与文档相关的任何反馈，欢迎通过此通道将它记录下来。 

非常感谢你对我们的文章作出的贡献。  

深深的祝福， 
Microsoft DOCS International Team
