### ISSUE TITLE
中文翻译有误

### ISSUE THREAD

**Issue by GZFrankPeng** [MicrosoftDocs/azure-docs.zh-cn#669]
自动缩放 中文翻译为：
Standard_v2 或 WAF_v2 SKU 下的应用程序网关或 WAF 部署支持自动缩放，可根据变化的流量负载模式进行【纵向】扩展或缩减。 纵向的翻译有误，英文原文中只是scale up or down，并无【纵向】的意思。

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 68677bfe-232b-3f9f-5473-005098e7231d
* Version Independent ID: ab0e9bbf-b9cd-acdc-054d-ca64bf6700bb
* Content: [Azure 应用程序网关的定义](https://docs.microsoft.com/zh-cn/azure/application-gateway/overview#feedback)
* Content Source: [articles/application-gateway/overview.md](https://github.com/MicrosoftDocs/azure-docs.zh-cn/blob/master/articles/application-gateway/overview.md)
* Service: **application-gateway**
* GitHub Login: @vhorne
* Microsoft Alias: **victorh**

**Comment by srvbpigh** [comment]
Hello, @GZFrankPeng
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by ticianaciminari** [comment]
你好，@GZFrankPeng

感谢你的反馈。 

我们语言专家团队已评审并接受你的语言相关建议。我们已实施你的反馈，并将更新后的文章发布到 Docs 站点上的以下页面：XXX。  

非常感谢你对我们的文章作出的贡献，欢迎继续提供宝贵的反馈。 


深深的祝福， 

Microsoft DOCS International Team
