### ISSUE TITLE
power错翻译为 幂

### ISSUE THREAD

**Issue by uingrd** [MicrosoftDocs/azure-docs.zh-cn#676]
power错翻译为 幂

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 2f1e9f4e-d338-c99d-ca23-a3d702a816d6
* Version Independent ID: 2cb57b44-8917-35f4-47d7-4e51d65cceca
* Content: [Azure Kinect DK Windows 版的比较](https://docs.microsoft.com/zh-cn/azure/kinect-dk/windows-comparison#feedback)
* Content Source: [articles/kinect-dk/windows-comparison.md](https://github.com/MicrosoftDocs/azure-docs.zh-cn/blob/master/articles/kinect-dk/windows-comparison.md)
* Product: **kinect-dk**
* GitHub Login: @tesych
* Microsoft Alias: **tesych**

**Comment by srvbpigh** [comment]
Hello, @uingrd
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
你好，@uingrd  

 

感谢你的反馈。  

 

我们语言专家团队已评审并接受你的语言相关建议。我们已实施你的反馈，并将更新后的文章发布到 Docs 站点上的以下页面：https://docs.microsoft.com/zh-cn/azure/kinect-dk/windows-comparison#feedback。   

 

非常感谢你对我们的文章作出的贡献，欢迎继续提供宝贵的反馈。  

 

 

深深的祝福，  

 

Microsoft DOCS International Team

**Comment by ticianaciminari** [comment]
你好，@uingrd 

感谢你的反馈。 

我们语言专家团队已评审并接受你的语言相关建议。我们已实施你的反馈，并将更新后的文章发布到 Docs 站点上的以下页面：https://docs.microsoft.com/zh-cn/azure/kinect-dk/windows-comparison#feedback。  

非常感谢你对我们的文章作出的贡献，欢迎继续提供宝贵的反馈。 


深深的祝福， 

Microsoft DOCS International Team
