### ISSUE TITLE
CopyData Activity 不支持覆盖 Sink 数据吗？

### ISSUE THREAD

**Issue by Mr-San** [MicrosoftDocs/azure-docs.zh-cn#677]
CopyData Activity 不支持覆盖 Sink 数据吗？数据采集应该分两种，全量覆盖和增量插入或合并

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 16b565fd-5303-cfcb-73f7-e2fd54a9c3a1
* Version Independent ID: bcbd827a-09e5-3990-2a42-1a0d35cc9415
* Content: [复制和转换 Azure Data Lake Storage Gen2 中的数据](https://docs.microsoft.com/zh-cn/azure/data-factory/connector-azure-data-lake-storage#feedback)
* Content Source: [articles/data-factory/connector-azure-data-lake-storage.md](https://github.com/MicrosoftDocs/azure-docs.zh-cn/blob/master/articles/data-factory/connector-azure-data-lake-storage.md)
* Service: **data-factory**
* GitHub Login: @linda33wj
* Microsoft Alias: **jingwang**

**Comment by srvbpigh** [comment]
Hello, @Mr-San
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
你好，@Mr-San

非常感谢你的参与。你的反馈与原始文档有关。 

因此，我们会将此问题迁移到英文版存储库。请在这里查看问题的状态 - https://github.com/MicrosoftDocs/azure-docs/issues/44426

非常感谢你对我们的文章作出的贡献。  


深深的祝福， 
Microsoft DOCS International Team
