### ISSUE TITLE
Execute Pipeline Activity 所在 Pipeline 最终执行状态 BUG

### ISSUE THREAD

**Issue by Mr-San** [MicrosoftDocs/azure-docs.zh-cn#678]
正常逻辑：Set variable Activity（ B ）-&gt; Hive Activity（ A ） ，活动 B 对活动 A 具有的依赖项条件为 “ 失败 ”，A 失败后，调用 B 成功，则 Pipeline 返回成功

发现 BUG：Set variable Activity（ B ）-&gt; Execute Pipeline Activity（ A ） ，活动 B 对活动 A 具有的依赖项条件为 “ 失败 ”，A 失败后，调用 B 成功，而 Pipeline 却返回失败 ？

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: ed77a05e-c9fd-ead1-d767-8b41be183634
* Version Independent ID: 0f61d8b7-2736-056c-b17e-ed7ad06a413e
* Content: [Azure 数据工厂中的 ](https://docs.microsoft.com/zh-cn/azure/data-factory/control-flow-execute-pipeline-activity#feedback)
* Content Source: [articles/data-factory/control-flow-execute-pipeline-activity.md](https://github.com/MicrosoftDocs/azure-docs.zh-cn/blob/master/articles/data-factory/control-flow-execute-pipeline-activity.md)
* Service: **data-factory**
* GitHub Login: @djpmsft
* Microsoft Alias: **daperlov**

**Comment by srvbpigh** [comment]
Hello, @Mr-San
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
你好，@Mr-San 

非常感谢你的参与。你的反馈与原始文档有关。  

因此，我们会将此问题迁移到英文版存储库。请在这里查看问题的状态 - https://github.com/MicrosoftDocs/azure-docs/issues/45546。  

非常感谢你对我们的文章作出的贡献。   

深深的祝福，  
Microsoft DOCS International Team
