### ISSUE TITLE
Chapter Title in Chinese should be "列级别安全性"

### ISSUE THREAD

**Issue by jerllllllllyn** [MicrosoftDocs/azure-docs.zh-cn#679]
Chapter Title in Chinese should be "列级别安全性"

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: d200cb5d-8f70-87c5-2437-c54701f7681f
* Version Independent ID: df184959-2b22-4796-c0b1-0a8ad91be35a
* Content: [行级别安全性](https://docs.microsoft.com/zh-cn/azure/sql-data-warehouse/column-level-security?view=sql-server-ver15#feedback)
* Content Source: [articles/sql-data-warehouse/column-level-security.md](https://github.com/MicrosoftDocs/azure-docs.zh-cn/blob/master/articles/sql-data-warehouse/column-level-security.md)
* Service: **sql-data-warehouse**
* Sub-service: **security**
* GitHub Login: @julieMSFT
* Microsoft Alias: **jrasnick**

**Comment by srvbpigh** [comment]
Hello, @jerllllllllyn
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @jerllllllllyn
I cannot repro this issue, the title reads "列级别安全性"
![imagen](https://user-images.githubusercontent.com/26746247/71905100-35e6a080-3146-11ea-89e3-627659165f14.png)

Can you please clarify your comment?

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @jerllllllllyn 
 
Thanks once again for your comment.
Unfortunately, we are still missing information and we are unable to process your feedback. We are closing this GitHub issue at this time but we encourage you to submit more feedback in the future.

Kind regards,
Microsoft DOCS International Team
