### ISSUE TITLE
无法离开组织

### ISSUE THREAD

**Issue by AbbyLiumm** [MicrosoftDocs/azure-docs.zh-cn#680]
我按照上面“离开组织”的流程，点击"leave organization"，但页面提示：“出现了意外错误。请重试。如果此问题一直存在，请联系支持人员。 ”  我也不知道应该联系谁，页面并没有任何可联系的方式以及可联系的地址。 我出现该问题的邮箱是：AbbyLiu.MSRA@outlook.com，我的组织当中有一个由我自己创建的 Free 组织，名叫：Test，如果有官方工作人员可以帮助我删除，那么就太好了，我会非常感谢你们。

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: b448cfd0-b673-7d04-047b-71aa62bebc27
* Version Independent ID: 75118bff-94de-c9f9-7666-d2a6f4253b11
* Content: [将组织作为来宾用户 Azure Active Directory](https://docs.microsoft.com/zh-cn/azure/active-directory/b2b/leave-the-organization#feedback)
* Content Source: [articles/active-directory/b2b/leave-the-organization.md](https://github.com/MicrosoftDocs/azure-docs.zh-cn/blob/master/articles/active-directory/b2b/leave-the-organization.md)
* Service: **active-directory**
* Sub-service: **b2b**
* GitHub Login: @msmimart
* Microsoft Alias: **mimart**

**Comment by srvbpigh** [comment]
Hello, @AbbyLiumm
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
你好，@AbbyLiumm

非常感谢您的贡献。此反馈与产品相关，请使用“文档”页底部的“提供产品反馈”按钮，记录你的建议。

如果你有任何与文档相关的反馈，请通过此渠道进行记录。

我们非常感谢你对我们的文章的贡献。

Microsoft DOCS 国际团队
