### ISSUE TITLE
Text chaos!Part of it is in Korean

### ISSUE THREAD

**Issue by ngelll** [MicrosoftDocs/azure-docs.zh-cn#681]
Text chaos!Part of it is in Korean

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 9461e901-80bd-8dbb-b866-76dd7f7fcef4
* Version Independent ID: 06daf40b-6a98-57bb-768d-6d296567f100
* Content: [Azure 표준 Load Balancer 및 가용성 영역 - Azure Load Balancer](https://docs.microsoft.com/zh-cn/azure/load-balancer/load-balancer-standard-availability-zones#feedback)
* Content Source: [articles/load-balancer/load-balancer-standard-availability-zones.md](https://github.com/MicrosoftDocs/azure-docs.zh-cn/blob/master/articles/load-balancer/load-balancer-standard-availability-zones.md)
* Service: **load-balancer**
* GitHub Login: @asudbring
* Microsoft Alias: **allensu**

**Comment by srvbpigh** [comment]
Hello, @ngelll
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
Thank you for your feedback. 

Our engineer team reviewed your suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/zh-cn/azure/load-balancer/load-balancer-standard-availability-zones#feedback.  

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback. 

Kind regards, 
Microsoft DOCS International Team
