### ISSUE TITLE
Korean???

### ISSUE THREAD

**Issue by v-tawe** [MicrosoftDocs/azure-docs.zh-cn#682]
I believe you translated into wrong language.

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 89142752-64bc-31c2-9189-aa2c2dcf2997
* Version Independent ID: 4ef63a3f-beca-e562-5e69-3cc931bd1022
* Content: [네트워킹 고려 사항](https://docs.microsoft.com/zh-cn/azure/app-service/environment/network-info#feedback)
* Content Source: [articles/app-service/environment/network-info.md](https://github.com/MicrosoftDocs/azure-docs.zh-cn/blob/master/articles/app-service/environment/network-info.md)
* GitHub Login: @ccompy
* Microsoft Alias: **ccompy**

**Comment by srvbpigh** [comment]
Hello, @v-tawe
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
Thank you for your feedback. 

Our engineer team reviewed your suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/zh-cn/azure/app-service/environment/network-info#feedback.  

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback. 

Kind regards, 
Microsoft DOCS International Team
