### ISSUE TITLE
图片显示问题

### ISSUE THREAD

**Issue by v-tawe** [MicrosoftDocs/azure-docs.zh-cn#698]
下面这个图片没有显示：

https://docs.microsoft.com/zh-cn/azure/search/search-create-index-portal#start-index-designer
![image](https://user-images.githubusercontent.com/22313449/75951423-fa1e4c00-5ee6-11ea-9119-5547f74bc459.png)

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 836fd03c-dad6-64cf-0ee0-2c288f572526
* Version Independent ID: 268f7887-819d-655b-170b-9fa9c9d95c2a
* Content: [在 Azure 门户中创建搜索索引 - Azure Cognitive Search](https://docs.microsoft.com/zh-cn/azure/search/search-create-index-portal#start-index-designer)
* Content Source: [articles/search/search-create-index-portal.md](https://github.com/MicrosoftDocs/azure-docs.zh-cn/blob/master/articles/search/search-create-index-portal.md)
* Service: **cognitive-search**
* GitHub Login: @HeidiSteen
* Microsoft Alias: **heidist**

**Comment by srvbpigh** [comment]
Hello, @v-tawe
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by v-tawe** [comment]
already fixed, so close this issue.
