### ISSUE TITLE
"更新 Azure 虚拟网络的 DNS 设置" 小节中的ip地址有错误

### ISSUE THREAD

**Issue by Shinji-IkariG** [MicrosoftDocs/azure-docs.zh-cn#699]
IP应为10.0.1.4、10.0.1.5而非10.1.0.4、10.1.0.5

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: ad393cc1-3395-fb17-b441-3d8998ed515b
* Version Independent ID: d4ebda6b-1528-e553-b37e-df586e6cb606
* Content: [教程 - 创建 Azure Active Directory 域服务实例](https://docs.microsoft.com/zh-cn/azure/active-directory-domain-services/tutorial-create-instance#feedback)
* Content Source: [articles/active-directory-domain-services/tutorial-create-instance.md](https://github.com/MicrosoftDocs/azure-docs.zh-cn/blob/master/articles/active-directory-domain-services/tutorial-create-instance.md)
* Service: **active-directory**
* Sub-service: **domain-services**
* GitHub Login: @iainfoulds
* Microsoft Alias: **iainfou**

**Comment by srvbpigh** [comment]
Hello, @Shinji-IkariG
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #49893](https://github.com/MicrosoftDocs/azure-docs/issues/49893) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
你好，@Shinji-IkariG 

非常感谢你的参与。你的反馈与原始文档有关。  

因此，我们会将此问题迁移到英文版存储库。请在这里查看问题的状态 - https://github.com/MicrosoftDocs/azure-docs/issues/49893。  

非常感谢你对我们的文章作出的贡献。   

深深的祝福，  
Microsoft DOCS International Team
