### ISSUE TITLE
Can't set CDN Resource group location

### ISSUE THREAD

**Issue by SunnyXiao** [MicrosoftDocs/azure-docs.zh-cn#700]
I can't change the resource group location when i create a new CDN profile with Microsoft CDN

![image](https://user-images.githubusercontent.com/18277688/75966110-c7834c00-5f04-11ea-89ca-e454428e3e02.png)

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 8cb1c7ba-83cb-e32a-85bd-3260bdefaee2
* Version Independent ID: a5229c23-ac2d-3972-6b54-d4e70db5c046
* Content: [快速入门 - 创建 Azure CDN 配置文件和终结点](https://docs.microsoft.com/zh-cn/azure/cdn/cdn-create-new-endpoint)
* Content Source: [articles/cdn/cdn-create-new-endpoint.md](https://github.com/MicrosoftDocs/azure-docs.zh-cn/blob/master/articles/cdn/cdn-create-new-endpoint.md)
* Service: **azure-cdn**
* GitHub Login: @mdgattuso
* Microsoft Alias: **magattus**

**Comment by srvbpigh** [comment]
Hello, @SunnyXiao
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @SunnyXiao 

Your contribution is highly appreciated. Yet, this feedback is related with product, please kindly log your suggestion by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.

We truly appreciate your contribution to our articles.

Microsoft DOCS International Team
