### ISSUE TITLE
typo in this page

### ISSUE THREAD

**Issue by ft1284595** [MicrosoftDocs/azure-docs.zh-cn#702]
서비스 태그 这个翻译不是中文。
서비스 태그 this is not Chinese.

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 5e905802-0b08-4b3b-25ec-0f88c023bc32
* Version Independent ID: f31325e5-49ea-b28c-336e-10f2a3fc12b4
* Content: [Azure 网络安全组概述](https://docs.microsoft.com/zh-cn/azure/virtual-network/security-overview#feedback)
* Content Source: [articles/virtual-network/security-overview.md](https://github.com/MicrosoftDocs/azure-docs.zh-cn/blob/master/articles/virtual-network/security-overview.md)
* Service: **virtual-network**
* GitHub Login: @KumudD
* Microsoft Alias: **kumud**

**Comment by srvbpigh** [comment]
Hello, @ft1284595
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @ft1284595

Thank you for your feedback. 

Our engineer team reviewed your suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/zh-cn/azure/virtual-network/security-overview#feedback

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback. 

Kind regards, 

Microsoft DOCS International Team
