### ISSUE TITLE
MSAL如何与公司内部登录系统进行集成

### ISSUE THREAD

**Issue by Sicmatr1x** [MicrosoftDocs/azure-docs.zh-cn#704]
公司内部登录系统支持OAuth2.0，现在需要在移动端使用MSAL来进行登录公司内部的登录系统

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: edb54089-d47b-3f58-a5e6-fb2e7f2691f1
* Version Independent ID: bfe2dfee-2a02-48ed-4cda-5f87d8be3527
* Content: [Microsoft 标识平台的发展 - Azure](https://docs.microsoft.com/zh-cn/azure/active-directory/develop/about-microsoft-identity-platform)
* Content Source: [articles/active-directory/develop/about-microsoft-identity-platform.md](https://github.com/MicrosoftDocs/azure-docs.zh-cn/blob/master/articles/active-directory/develop/about-microsoft-identity-platform.md)
* Service: **active-directory**
* Sub-service: **develop**
* GitHub Login: @rwike77
* Microsoft Alias: **ryanwi**

**Comment by srvbpigh** [comment]
Hello, @Sicmatr1x
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
你好，@Sicmatr1x

非常感谢您的贡献。此反馈与产品相关，请使用“文档”页底部的“提供产品反馈”按钮，记录你的建议。

如果你有任何与文档相关的反馈，请通过此渠道进行记录。

我们非常感谢你对我们的文章的贡献。

Microsoft DOCS 国际团队
