### ISSUE TITLE
翻译错误

### ISSUE THREAD

**Issue by fushuang001** [MicrosoftDocs/azure-docs.zh-cn#705]
使用网络完全组 (NSG) 保护 VNet &lt;&lt;&lt;&lt;&lt;&lt; 网络安全组

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: f03f79a2-923f-3e1a-5e8f-8ce1f5913a56
* Version Independent ID: 6330e3e6-d903-b8f8-370d-e61ff4384d5e
* Content: [Azure 虚拟网络](https://docs.microsoft.com/zh-cn/azure/virtual-network/virtual-networks-overview?source=docs#feedback)
* Content Source: [articles/virtual-network/virtual-networks-overview.md](https://github.com/MicrosoftDocs/azure-docs.zh-cn/blob/master/articles/virtual-network/virtual-networks-overview.md)
* Service: **virtual-network**
* GitHub Login: @anavinahar
* Microsoft Alias: **anavin**

**Comment by srvbpigh** [comment]
Hello, @fushuang001
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
你好，@fushuang001  

感谢你的反馈。  

我们语言专家团队已评审并接受你的语言相关建议。我们已实施你的反馈，并将更新后的文章发布到 Docs 站点上的以下页面：https://docs.microsoft.com/zh-cn/azure/virtual-network/virtual-networks-overview?source=docs#feedback。   

非常感谢你对我们的文章作出的贡献，欢迎继续提供宝贵的反馈。  

深深的祝福，  
Microsoft DOCS International Team
