### ISSUE TITLE
“预测测试数据”步骤报错

### ISSUE THREAD

**Issue by gaozhao98** [MicrosoftDocs/azure-docs.zh-cn#706]
使用azure自带jupyter notebook，按照本教程进行到“预测测试数据”时，报错ModuleNotFoundError: No module named 'sklearn.linear_model._logistic'

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 89cb4f9c-34e0-b4df-f911-e083c420cee8
* Version Independent ID: 5be8b3bb-fb17-175a-7ca0-d69cef414799
* Content: [图像分类教程：部署模型 - Azure Machine Learning](https://docs.microsoft.com/zh-cn/azure/machine-learning/tutorial-deploy-models-with-aml)
* Content Source: [articles/machine-learning/tutorial-deploy-models-with-aml.md](https://github.com/MicrosoftDocs/azure-docs.zh-cn/blob/master/articles/machine-learning/tutorial-deploy-models-with-aml.md)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @sdgilley
* Microsoft Alias: **sgilley**

**Comment by srvbpigh** [comment]
Hello, @gaozhao98
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by V-vafune** [comment]
こんにちは、@gaozhao98  

 ご協力に深く感謝いたします。Microsoft の担当チームでは、ドキュメントに関するフィードバックに対してのみお答えすることができます。  

 ドキュメント ページの下部にある [製品のフィードバックを送信] ボタンを使用して、製品に関するフィードバックをログに記録してください。  

 ドキュメントに関するフィードバックがある場合は、このチャンネルをご自由に使用して、内容をログに記録してください。  

 記事の品質向上にご協力いただき誠にありがとうございました。   

 敬具  

Microsoft DOCS International Team
