### ISSUE TITLE
wrong code snippet selected

### ISSUE THREAD

**Issue by v-tawe** [MicrosoftDocs/azure-docs.zh-cn#707]
https://docs.microsoft.com/zh-cn/azure/governance/policy/samples/pattern-effect-details#sample-1-explanation
This section should use below code snippet I guess:
```json
           "then": {
               "effect": "modify",
               "details": {
                   "roleDefinitionIds": [
                       "/providers/microsoft.authorization/roleDefinitions/b24988ac-6180-42a0-ab88-20f7382dd24c"
                   ],
                   "operations": [{
                       "operation": "add",
                       "field": "[concat('tags[', parameters('tagName'), ']')]",
                       "value": "[parameters('tagValue')]"
                   }]
               }
           }
```

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 94ee5644-f318-7bad-d211-3c1ae6c3155d
* Version Independent ID: a57a8908-e308-4db4-1ee2-6ff26bec0988
* Content: [模式：策略定义的效果 - Azure Policy](https://docs.microsoft.com/zh-cn/azure/governance/policy/samples/pattern-effect-details#sample-1-explanation)
* Content Source: [articles/governance/policy/samples/pattern-effect-details.md](https://github.com/MicrosoftDocs/azure-docs.zh-cn/blob/master/articles/governance/policy/samples/pattern-effect-details.md)

**Comment by srvbpigh** [comment]
Hello, @v-tawe
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #51108](https://github.com/MicrosoftDocs/azure-docs/issues/51108) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
Hello, @v-tawe, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/51108. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
