### ISSUE TITLE
Chinese document translation bug

### ISSUE THREAD

**Issue by leonlj** [MicrosoftDocs/azure-docs.zh-cn#709]
1. Train was translated to 火车 wrongly. Please review the translation result again 

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 134791cd-db3b-b729-607e-22be8dcddf9a
* Version Independent ID: bed88b29-334f-6a9a-912f-1487da4afa14
* Content: [体系结构和重要概念 - Azure Machine Learning](https://docs.microsoft.com/zh-cn/azure/machine-learning/concept-azure-machine-learning-architecture#feedback)
* Content Source: [articles/machine-learning/concept-azure-machine-learning-architecture.md](https://github.com/MicrosoftDocs/azure-docs.zh-cn/blob/master/articles/machine-learning/concept-azure-machine-learning-architecture.md)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @Blackmist
* Microsoft Alias: **larryfr**

**Comment by srvbpigh** [comment]
Hello, @leonlj
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello @leonlj 

Thank you for your contribution. 

Contributions on translation problems against machine translated content are currently not accepted. 

We value your feedback and suggestions on human translated content, which is used to train the machine translation engines, so over time, your contributions will improve the quality of both human and machine translations. 

Human translated topics can be distinguished from machine translated topics by the ms.translationtype metadata value “HT” (versus “MT” for machine translated) in the header of each content file. 

Many thanks for your support. 

Microsoft DOCS Global Experience Team
