### ISSUE TITLE
the api string concat is error

### ISSUE THREAD

**Issue by guodan** [MicrosoftDocs/azure-docs.zh-cn#710]
the computer-vision endpoint where I applid is ‘https://westcentralus.api.cognitive.microsoft.com/vision’ ，and it's end with  "vision". But the demo code is

`const uriBase = endpoint + "vision/v2.1/analyze"`,

the 'vision' is duplicate

**Comment by srvbpigh** [comment]
Hello, @guodan
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #52016](https://github.com/MicrosoftDocs/azure-docs/issues/52016) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
Hello, @guodan, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/52016. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team

**Comment by guodan** [comment]
Hi @RohitMungi-MSFT , I have tested my company account's endpoint is right, so the demo in documentation is right too. 
My personal account of computer-vision's endpoint which can only user 7 days is error.
The endpoint is "https://westcentralus.api.cognitive.microsoft.com/vision",it should'n contain "vision".

demo link:
[https://docs.microsoft.com/zh-cn/azure/cognitive-services/Computer-vision/quickstarts/node-analyze](url)

**Comment by RohitMungi-MSFT** [comment]
@guodan The endpoint should be the URL that you can copy from the Azure portal and it should work as mentioned. I am not sure if vision is added as part of the endpoint name if you lookup the same in azure portal. Could you please check and use the endpoint as available from the portal?
