### ISSUE TITLE
根本无法运行，求助

### ISSUE THREAD

**Issue by appleyuchi** [MicrosoftDocs/azure-docs.zh-cn#711]
[在此处输入反馈]

python代码无法运行：
(Python2.7) appleyuchi@ubuntu19:bing的搜索API用法$ python test.py 
  File "test.py", line 10
    client = WebSearchClient(endpoint="YOUR_ENDPOINT",CognitiveServicesCredentials(subscription_key))
SyntaxError: non-keyword arg after keyword arg

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 73a384e5-1447-14f0-e55d-37d7c4c6ea1f
* Version Independent ID: 2fe02dc2-b1db-14c1-543f-add375503d40
* Content: [快速入门：使用必应 Web 搜索客户端库 - Azure Cognitive Services](https://docs.microsoft.com/zh-cn/azure/cognitive-services/bing-web-search/quickstarts/client-libraries?pivots=programming-language-python#feedback)
* Content Source: [articles/cognitive-services/Bing-Web-Search/quickstarts/client-libraries.md](https://github.com/MicrosoftDocs/azure-docs.zh-cn/blob/master/articles/cognitive-services/Bing-Web-Search/quickstarts/client-libraries.md)
* Service: **cognitive-services**
* Sub-service: **bing-web-search**
* GitHub Login: @aahill
* Microsoft Alias: **aahi**

**Comment by srvbpigh** [comment]
Hello, @appleyuchi
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #52018](https://github.com/MicrosoftDocs/azure-docs/issues/52018) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
你好，@appleyuchi 

非常感谢你的参与。你的反馈与原始文档有关。  

因此，我们会将此问题迁移到英文版存储库。请在这里查看问题的状态 - https://github.com/MicrosoftDocs/azure-docs/issues/52018。  

非常感谢你对我们的文章作出的贡献。   

深深的祝福，  
Microsoft DOCS International Team
