### ISSUE TITLE
train翻译错误

### ISSUE THREAD

**Issue by lawup** [MicrosoftDocs/azure-docs.zh-cn#713]
[在此处输入反馈]

生成自定义语音模型
验证数据集后，可以使用它来生成自定义语音模型。
导航到“文本转语音”>“自定义语音”>“训练”。****
单击 "火车"模型。

关于“train”
这里的“火车”应该翻译为“训练”

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 5f0fa35c-379f-a8e4-01ec-fb5658ea81e7
* Version Independent ID: a17d066a-0c65-b956-ed1a-8503e3e17f6f
* Content: [创建自定义语音 - 语音服务 - Azure Cognitive Services](https://docs.microsoft.com/zh-cn/azure/cognitive-services/speech-service/how-to-custom-voice-create-voice)
* Content Source: [articles/cognitive-services/Speech-Service/how-to-custom-voice-create-voice.md](https://github.com/MicrosoftDocs/azure-docs.zh-cn/blob/master/articles/cognitive-services/Speech-Service/how-to-custom-voice-create-voice.md)
* Service: **cognitive-services**
* Sub-service: **speech-service**
* GitHub Login: @erhopf
* Microsoft Alias: **erhopf**

**Comment by srvbpigh** [comment]
Hello, @lawup
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
你好，@lawup

感谢你的发布内容。 

当前不接受有关机器翻译内容的翻译问题的发布内容。 

我们重视你对人工翻译内容（用于训练机器翻译引擎）的反馈和建议，你的参与将逐渐提高人工翻译和机器翻译的质量。 

人工翻译主题可以通过每个内容文件标题中的 ms.translationtype 元数据值“HT”与机器翻译主题（使用“MT”作为元数据值）区别开。 

非常感谢你的支持。 

 

Microsoft DOCS 全球体验团队
