### ISSUE TITLE
Only the same AAD？

### ISSUE THREAD

**Issue by Tank1719248** [MicrosoftDocs/azure-docs.zh-cn#718]
This script is limited to the same AAD? What if the different AADs are between them?

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: e429552f-202b-40e1-d624-16bb7731c38f
* Version Independent ID: abafe3ce-ff54-57d3-cc2c-0433774d2ff0
* Content: [将托管磁盘复制到订阅 - PowerShell 示例](https://docs.microsoft.com/zh-cn/azure/virtual-machines/scripts/virtual-machines-windows-powershell-sample-copy-managed-disks-to-same-or-different-subscription#feedback)
* Content Source: [articles/virtual-machines/scripts/virtual-machines-windows-powershell-sample-copy-managed-disks-to-same-or-different-subscription.md](https://github.com/MicrosoftDocs/azure-docs.zh-cn/blob/master/articles/virtual-machines/scripts/virtual-machines-windows-powershell-sample-copy-managed-disks-to-same-or-different-subscription.md)
* Service: **virtual-machines-windows**
* GitHub Login: @ramankumarlive
* Microsoft Alias: **ramankum**

**Comment by srvbpigh** [comment]
Hello, @Tank1719248
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by Tank1719248** [comment]
Hi
   I've used Azcopy to solve this problem,  thank you for your documentation and advice.

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: srvbpigh<mailto:notifications@github.com>
发送时间: 2020年4月26日 15:16
收件人: MicrosoftDocs/azure-docs.zh-cn<mailto:azure-docs.zh-cn@noreply.github.com>
抄送: Tank1719248<mailto:Tank_T@outlook.com>; Mention<mailto:mention@noreply.github.com>
主题: Re: [MicrosoftDocs/azure-docs.zh-cn] Only the same AAD？ (#718)


Hello, @Tank1719248<https://github.com/Tank1719248>

Thank you for your feedback.

We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

―

**Comment by CeciAc** [comment]
Hello, @Tank1719248 
Your feedback is much appreciated. We are glad to see that your experience with our documentation meets your expectations. 
We encourage you to provide your valuable feedback so that we can continue improve your experience. 

Kind regards, 

Microsoft DOCS International Team
