### ISSUE TITLE
如何从电源应用查询认知搜索索引

### ISSUE THREAD

**Issue by v-tawe** [MicrosoftDocs/azure-docs.zh-cn#719]
好一个"**电源应用**"！

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: cb19d5c9-3984-1743-7678-a8ed6ae2bf66
* Version Independent ID: 768d6097-6f0c-13fb-f901-dae7fc82eaa8
* Content: [如何从电源应用查询 Azure 认知搜索 - Azure Cognitive Search](https://docs.microsoft.com/zh-cn/azure/search/search-howto-powerapps)
* Content Source: [articles/search/search-howto-powerapps.md](https://github.com/MicrosoftDocs/azure-docs.zh-cn/blob/master/articles/search/search-howto-powerapps.md)
* Service: **cognitive-search**
* GitHub Login: @LuisCabrer
* Microsoft Alias: **luisca**

**Comment by srvbpigh** [comment]
Hello, @v-tawe
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
你好，@v-tawe

非常感谢你提供反馈。很高兴我们的文档满足你的期望。  

欢迎提供宝贵的反馈，以便我们继续改进体验。  
 
深深的祝福，  

Microsoft DOCS International Team
