### ISSUE TITLE
Proper Nouns Should Not Be Machine-Translated

### ISSUE THREAD

**Issue by VaslD** [MicrosoftDocs/azure-docs.zh-cn#720]
On some pages of Azure documentation (including this one), *PowerShell* is incorrectly translated to Simplified Chinese as *电源外壳* (lit. electric power case). This is confusing, jarring, and somewhat gravely misleading if people took things literally. 🤣 

If you're doing automatic machine translation, at least exclude known proper nouns (including but not limited to product names, some technical terms and stuff that are simply made-up) from going through auto translation.

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 6ee9ec76-a91f-095a-5ba3-b9c413366751
* Version Independent ID: 29c17263-ed56-d42e-bc3f-091ef2b4b9ff
* Content: [创建存储帐户 - Azure Storage](https://docs.microsoft.com/zh-cn/azure/storage/common/storage-account-create?toc=%2Fazure%2Fstorage%2Fblobs%2Ftoc.json&tabs=azure-portal#feedback)
* Content Source: [articles/storage/common/storage-account-create.md](https://github.com/MicrosoftDocs/azure-docs.zh-cn/blob/master/articles/storage/common/storage-account-create.md)
* Service: **storage**
* Sub-service: **common**
* GitHub Login: @tamram
* Microsoft Alias: **tamram**

**Comment by srvbpigh** [comment]
Hello, @VaslD
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello @VaslD 

Thank you for your contribution. 

Contributions on translation problems against machine-translated content are currently not accepted. 

We value your feedback and suggestions on human translated content, which is used to train the machine translation engines, so over time, your contributions will improve the quality of both human and machine translations. 

Human translated topics can be distinguished from machine-translated topics by the ms.translationtype metadata value “HT” (versus “MT” for machine translated) in the header of each content file. 

Many thanks for your support. 

Microsoft DOCS Global Experience Team
