### ISSUE TITLE
无法访问此网站az416426.vo.msecnd.net 的响应时间过长。

### ISSUE THREAD

**Issue by li10217** [MicrosoftDocs/azure-docs.zh-cn#721]
![image](https://user-images.githubusercontent.com/23067397/81272917-be3b6a80-9080-11ea-97f9-f8cc2487a6b1.png)

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: d56ecb14-9e66-5313-a381-d2824ec3d1e2
* Version Independent ID: ff056ac8-ae76-be10-6895-757333a28e05
* Content: [适用于 JavaScript web 应用的 Azure 应用程序 Insights](https://docs.microsoft.com/zh-cn/azure/azure-monitor/app/javascript)
* Content Source: [articles/azure-monitor/app/javascript.md](https://github.com/MicrosoftDocs/azure-docs.zh-cn/blob/master/articles/azure-monitor/app/javascript.md)
* GitHub Login: @DawgFan
* Microsoft Alias: **mmcc**

**Comment by srvbpigh** [comment]
Hello, @li10217
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by DawgFan** [comment]
@xiao-lix Can you help? Feel free to create a DevOps task, raise to Ram.

**Comment by CeciAc** [comment]
你好，@li10217

非常感谢你的参与。你的反馈与原始文档有关。  

因此，我们会将此问题迁移到英文版存储库。请在这里查看问题的状态 - https://github.com/MicrosoftDocs/azure-docs/issues/54371

非常感谢你对我们的文章作出的贡献。   

深深的祝福，  

Microsoft DOCS International Team
