### ISSUE TITLE
Translation improvement

### ISSUE THREAD

**Issue by HaoHoo** [MicrosoftDocs/azure-docs.zh-cn#733]
选择是要使用 PYTHON sdk 还是 studio web 体验：了解python sdk 和 studio web 体验之间的奇偶校验。
-》选择使用 PYTHON sdk 还是 studio web 体验：了解python sdk 和 studio web 体验之间的差异。

如果有限制或没有代码体验，请尝试在 Azure 机器学习 studio web 体验https://ml.azure.com
-》如果有限制或没有代码经验，请尝试在 Azure 机器学习 studio web 体验 https://ml.azure.com

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: d2fcbcc1-0824-1dba-f5ae-6cf5c97a9d2c
* Version Independent ID: 0de15ea0-6def-bf7e-2e68-ae7d434d2d4b
* Content: [什么是自动化 ML/AutoML - Azure Machine Learning](https://docs.microsoft.com/zh-cn/azure/machine-learning/concept-automated-ml#imbalance)
* Content Source: [articles/machine-learning/concept-automated-ml.md](https://github.com/MicrosoftDocs/azure-docs.zh-cn/blob/master/articles/machine-learning/concept-automated-ml.md)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @cartacioS
* Microsoft Alias: **sacartac**

**Comment by srvbpigh** [comment]
Hello, @HaoHoo
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
Hello, @HaoHoo
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by v-radelg** [comment]
Hello @HaoHoo :

Thank you for your contribution.

Contributions on translation problems against machine translated content are currently not accepted.

We value your feedback and suggestions on human translated content, which is used to train the machine translation engines, so over time, your contributions will improve the quality of both human and machine translations.

Human translated topics can be distinguished from machine translated topics by the ms.translationtype metadata value “HT” (versus “MT” for machine translated) in the header of each content file.

Many thanks for your support.

Microsoft DOCS Global Experience Team

CC @ishasahni1
