### ISSUE TITLE
翻译地一点都不准确

### ISSUE THREAD

**Issue by xgqfrms** [MicrosoftDocs/azure-docs.zh-cn#734]
# 翻译地一点都不准确

https://github.com/MicrosoftDocs/azure-docs.zh-cn/blob/master/articles/cost-management-billing/manage/cancel-azure-subscription.md

**Comment by xgqfrms** [comment]
# 取消 Azure 订阅

根本就找不到 cancel 的入口

https://docs.microsoft.com/en-us/azure/cost-management-billing/manage/cancel-azure-subscription

**Comment by xgqfrms** [comment]
界面都不一样

![image](https://user-images.githubusercontent.com/7291672/83321497-b7200a80-a282-11ea-9909-39a5e77ed69f.png)

**Comment by srvbpigh** [comment]
Hello, @xgqfrms
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by xgqfrms** [comment]
![image](https://user-images.githubusercontent.com/7291672/83328699-8c9c7480-a2b7-11ea-9d82-dc8daf73796e.png)

**Comment by V-vafune** [comment]
你好，@xgqfrms  

非常感谢你提供反馈。很高兴我们的文档满足你的期望。  

欢迎提供宝贵的反馈，以便我们继续改进体验。  

深深的祝福，  

Microsoft DOCS International Team
