### ISSUE TITLE
Wrong Chinese Neural voice names in zn-cn page (it's correct on en-us page)

### ISSUE THREAD

**Issue by dargilco** [MicrosoftDocs/azure-docs.zh-cn#735]
[在此处输入反馈]

The en-us docs page is correct with regards to Chinese Neural voice names, but the zn-cn is not. The Chinese page should say ""zh-CN-xxxxx" not ""zh-chs-xxxx":
https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/language-support#neural-voices
https://docs.microsoft.com/zh-cn/azure/cognitive-services/speech-service/language-support#neural-voices
This was reported on GitHub by a customer:
https://github.com/Azure-Samples/Cognitive-Services-Voice-Assistant/issues/462

Please check all other TTS pages to make sure they are correct.

Thanks,

Darren

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 4de08d1f-8114-7bef-7ef4-022f79c69742
* Version Independent ID: 4c0ceab9-24ed-de01-db30-31acf1de0f48
* Content: [语言支持 - 语音服务 - Azure Cognitive Services](https://docs.microsoft.com/zh-cn/azure/cognitive-services/speech-service/language-support#neural-voices)
* Content Source: [articles/cognitive-services/Speech-Service/language-support.md](https://github.com/MicrosoftDocs/azure-docs.zh-cn/blob/master/articles/cognitive-services/Speech-Service/language-support.md)
* Service: **cognitive-services**
* Sub-service: **speech-service**
* GitHub Login: @trevorbye
* Microsoft Alias: **trbye**

**Comment by srvbpigh** [comment]
Hello, @dargilco
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello @dargilco 

Thank you for your contribution.

Contributions on translation problems against machine-translated content are currently not accepted.

We value your feedback and suggestions on human translated content, which is used to train the machine translation engines, so over time, your contributions will improve the quality of both human and machine translations.

Human translated topics can be distinguished from machine translated topics by the ms.translationtype metadata value “HT” (versus “MT” for machine translated) in the header of each content file.

Many thanks for your support.

Microsoft DOCS Global Experience Team

**Comment by dargilco** [comment]
@CeciAc The issue has been fixed. Okay to close this.
