### ISSUE TITLE
powershell should not be translated as "电源外壳"

### ISSUE THREAD

**Issue by batkiz** [MicrosoftDocs/azure-docs.zh-cn#737]
powershell is just powershell, it doesn't have an official name in Chinese, don't translate it.

本页面中powershell被翻译为“电源外壳”，powerhsell core被翻译为“电源外壳核心”，这两者不应该被翻译。

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 40e84dea-0cdb-2aa7-6aa0-a4c697ef19ac
* Version Independent ID: 2fe0dbd3-7e5b-04b1-46e5-fecd89c4a780
* Content: [Azure Functions 中支持的语言](https://docs.microsoft.com/zh-cn/azure/azure-functions/supported-languages#languages-in-runtime-1x-and-2x)
* Content Source: [articles/azure-functions/supported-languages.md](https://github.com/MicrosoftDocs/azure-docs.zh-cn/blob/master/articles/azure-functions/supported-languages.md)
* Service: **azure-functions**
* GitHub Login: @ggailey777
* Microsoft Alias: **glenga**

**Comment by srvbpigh** [comment]
你好，@batkiz，

我们正在改进我们的内部流程和工程管道。遗憾的是，这会导致我们延迟处理你的反馈。

非常感谢你为我们的文章贡献内容，我们期待继续获取你的支持和理解。

**Comment by batkiz** [comment]
fixed
