### ISSUE TITLE
Is it available in the IPs form corresponding to the URLs?

### ISSUE THREAD

**Issue by Johnnytechn** [MicrosoftDocs/azure-docs.zh-cn#754]
There is now a scenario where the customer's proxy does not support domain name or URL settings. Is it available in the IPs form corresponding to the following URLs?

URLs 
www.msftncsi.com
*.Microsoft.com
*.WindowsAzure.com
*.microsoftonline.com
*.windows.net
www.msftconnecttest.com
IP addresses 
20.190.128.0/18
40.126.0.0/18

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 59cde3ab-f5bb-a7a3-3b14-40a87b9efcb3
* Version Independent ID: 2ccbb179-0216-346a-a56f-c03b3eafd57e
* Content: [安装 Microsoft Azure 恢复服务 (MARS) 代理 - Azure Backup](https://docs.microsoft.com/zh-cn/azure/backup/install-mars-agent#verify-internet-access)
* Content Source: [articles/backup/install-mars-agent.md](https://github.com/MicrosoftDocs/azure-docs.zh-cn/blob/master/articles/backup/install-mars-agent.md)
* Service: **backup**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
#reassign:utraghuv

**Comment by dcurwin** [comment]
#assign:utraghuv

**Comment by dcurwin** [comment]
If the customer can ensure that name resolution for the URLs will work but they still need to add the IPs specifically, they can track and use the service specific IPs listed in our Azure IP range doc. These service IP addresses can unfortunately change without notice so the list is kept updated every week.

Azure IP Range list : https://www.microsoft.com/en-us/download/details.aspx?id=56519

Service IDs : AzureBackup, Storage and AzureActiveDirectory

**Comment by dcurwin** [comment]
#please-close

**Comment by Johnnytechn** [comment]
I'm glad you can help, I think your answer has solved the problem. But there's a question, can you help me make a confirmation?
I've looked through the details of the link you've provided. Is the ultimate purpose of updating the IP Range list file every week to add some new Ips? The existing Ips are usually unchanged, Do I have the correct understanding of the IP Range list file?

**Comment by dcurwin** [comment]
Yes, from what I can tell you have the correct understanding, but it is still worth looking at the entire list of IPs.

**Comment by Johnnytechn** [comment]
@dcurwin  Ok, thank you very much for your help.

**Comment by Johnnytechn** [comment]
From [this link](https://github.com/MicrosoftDocs/azure-docs/issues/41572), I know the role of the above URLs. Some of these URLs are used for authenticating machines with the Azure Backup service while others are used to send data to managed-backup storage. Now the problem is here, how do I confirm from the IP Range list file which IPs correspond to the above URL?  I I can only confirm the IPs related to the "AzureBackup" service from the IP Range list file, but how other IPs should be confirmed(such as "*.Microsoft.com")? Is it necessary to configure all IPs in the IP Range list file within the operating system? Please help me make a confirmation. @dcurwin

**Comment by dcurwin** [comment]
This is the update I received regarding your question:

Due to location and load based routing, it is impossible to state with any certainty which ones would be the only ones used. Hence, there isn’t an easy way to narrow this down to a few IPs. They could monitor network traffic a few times and start with that subset but there is always a risk that something might break after routine service side updates.

**Comment by Johnnytechn** [comment]
Well, is it possible to give a definite IP list corresponding to all the URLs above for a particular region(such as chinaeast)? @dcurwin

**Comment by dcurwin** [comment]
#please-close

**Comment by dcurwin** [comment]
@v-amallick Please investigate and see if this is still an issue.
