### ISSUE TITLE
The pre-registration script

### ISSUE THREAD

**Issue by Johnnytechn** [MicrosoftDocs/azure-docs.zh-cn#759]
Is the **pre-registration script** download from [this link](https://aka.ms/scriptforpermsonhana) in [this article](https://docs.microsoft.com/zh-cn/azure/backup/tutorial-backup-sap-hana-db#what-the-pre-registration-script-does) available to run in sovereign clouds? If not, can you provide the download links for sovereign clouds? Thanks in advance!

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: d5d16f95-6c6c-aad4-7c98-b434327fee2c
* Version Independent ID: 2de588d0-81a3-ca99-67ab-267e0cdd42ff
* Content: [教程 - 备份 Azure VM 中的 SAP HANA 数据库 - Azure Backup](https://docs.microsoft.com/zh-cn/azure/backup/tutorial-backup-sap-hana-db#what-the-pre-registration-script-does)
* Content Source: [articles/backup/tutorial-backup-sap-hana-db.md](https://github.com/MicrosoftDocs/azure-docs.zh-cn/blob/master/articles/backup/tutorial-backup-sap-hana-db.md)
* Service: **backup**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
#reassign:pvrk

**Comment by pvrk** [comment]
@Johnnytechn : The script could be downloaded from sovereign regions as well. However, there is a network check section in script which is currently not updated with sovereign clouds. But you could skip that (--skip-network-checks option) and continue to run the rest of the script and enable backups. Please let me know if there is any issue.

**Comment by Johnnytechn** [comment]
@pvrk Ok, thanks for your response.
