### ISSUE TITLE
发布之后Function App中没有函数

### ISSUE THREAD

**Issue by kitcoun** [MicrosoftDocs/azure-docs.zh-cn#77]
发布之后Function App中没有函数

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 369aefa6-74da-3001-f835-15abdfffd5d6
* Version Independent ID: 2cc2a2db-d059-3252-7a1a-4261b7d3c37c
* Content: [使用 Visual Studio 开发 Azure Functions](https://docs.microsoft.com/zh-cn/azure/azure-functions/functions-develop-vs)
* Content Source: [articles/azure-functions/functions-develop-vs.md](https://github.com/MicrosoftDocs/azure-docs.zh-cn/blob/live/articles/azure-functions/functions-develop-vs.md)
* Service: **functions**
* Product: **unspecified**
* GitHub Login: @ggailey777
* Microsoft Alias: **glenga**

**Comment by CeciAc** [comment]
@kitcoun 
您好，谢谢您的反馈。我们需要更多信息才能处理这个问题；您能否提供更加详细的说明？

深深的祝福，
--
 
Microsoft DOCS International   Team

**Comment by CeciAc** [comment]
@kitcoun
您好，谢谢您的反馈。我们需要更多信息才能处理这个问题；您能否提供更加详细的说明？

深深的祝福， 
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
我们没有足够的信息来解决这个问题。

深深的祝福，
Microsoft DOCS International Team
