### ISSUE TITLE
郭小菲

### ISSUE THREAD

**Issue by gxf3gxf3** [MicrosoftDocs/azure-docs.zh-cn#78]
[在此处输入反馈]

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 78899009-3148-e888-cc84-8955e19fe48c
* Version Independent ID: 3ff29dd0-e8a4-63e6-a100-097c350b2e25
* Content: [Microsoft Authenticator 应用手机版](https://docs.microsoft.com/zh-cn/azure/multi-factor-authentication/end-user/microsoft-authenticator-app-how-to)
* Content Source: [articles/multi-factor-authentication/end-user/microsoft-authenticator-app-how-to.md](https://github.com/MicrosoftDocs/azure-docs.zh-cn/blob/live/articles/multi-factor-authentication/end-user/microsoft-authenticator-app-how-to.md)
* Service: **multi-factor-authentication**
* Product: **unspecified**
* GitHub Login: @barlanmsft
* Microsoft Alias: **barlan**

**Comment by CeciAc** [comment]
您好，@gxf3gxf3
谢谢您的反馈。我们需要更多信息才能处理这个问题；您能否提供更加详细的说明？

深深的祝福， 
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
们没有足够的信息来解决这个问题。
