### ISSUE TITLE
I won't find the stored data from my blob storage

### ISSUE THREAD

**Issue by Sannioy** [MicrosoftDocs/azure-docs.zh-cn#82]
Hi, I see this sentence from your document，“through the stream, into a blob for download”, but I won't find my devices data in my blob. What should I do to store edgeHub data in my blob? I'm looking forward to getting your reply, Thx.

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 6c6c2a4f-2979-8420-115c-852bee17e43b
* Version Independent ID: 01b5c8c0-4f08-53f7-7be7-a22038ad6988
* Content: [使用 Azure IoT Edge 部署 Azure 流分析](https://docs.microsoft.com/zh-cn/azure/iot-edge/tutorial-deploy-stream-analytics)
* Content Source: [articles/iot-edge/tutorial-deploy-stream-analytics.md](https://github.com/MicrosoftDocs/azure-docs.zh-cn/blob/live/articles/iot-edge/tutorial-deploy-stream-analytics.md)
* Service: **iot-edge**
* Product: **unspecified**
* GitHub Login: @kgremban
* Microsoft Alias: **kgremban**

**Comment by CeciAc** [comment]
Hello, @Sannioy,
Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team

**Comment by Sannioy** [comment]
Many thanks! I'll try this way.
