### ISSUE TITLE
Connect-AzureRmAccount Failed

### ISSUE THREAD

**Issue by xiaowei90113** [MicrosoftDocs/azure-docs.zh-cn#92]
I'm using powershell on Mac OS, and have Azure PowerShell module installed. By using  Get-Module -ListAvailable AzureRM  command I got the version is 6.3.0. But I failed with Connect-AzureRmAccount, it ran into an CommandNotFoundException.

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 55e23176-40c4-39bd-4f6f-cc48e518cf96
* Version Independent ID: 370fcf36-dce0-6718-4566-34a71cd0314e
* Content: [教程 - 使用 Azure PowerShell 创建和管理 Windows VM](https://docs.microsoft.com/zh-cn/azure/virtual-machines/windows/tutorial-manage-vm)
* Content Source: [articles/virtual-machines/windows/tutorial-manage-vm.md](https://github.com/MicrosoftDocs/azure-docs.zh-cn/blob/live/articles/virtual-machines/windows/tutorial-manage-vm.md)
* Service: **virtual-machines-windows**
* GitHub Login: @iainfoulds
* Microsoft Alias: **iainfou**

**Comment by gosali** [comment]
Hello, @xiaowei90113 , 

 Your contribution is much appreciated. Our team can only answer feedback related to the documentation. 

Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page. 
 

If you have any feedback related to the documentation, please feel free to log it through this channel. 

We truly appreciate your contribution to our articles.  
 
@SunnyDeng 
Kind regards, 

Microsoft DOCS International Team
