### ISSUE TITLE
翻译瑕疵 -- a translation flaw

### ISSUE THREAD

**Issue by dusmart** [MicrosoftDocs/azure-docs.zh-cn#97]
https://docs.microsoft.com/zh-cn/azure/storage/common/storage-concurrency?toc=%2fazure%2fstorage%2fblobs%2ftoc.json#overview

第三点的翻译不太准确，应该是[后写的人赢]，而不是[上次编写者赢]

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: cd5ebd41-40e7-0f94-2090-71151bd0b4f4
* Version Independent ID: 85128309-6794-8ce5-1504-cd31513c80e8
* Content: [在 Microsoft Azure 存储中管理并发](https://docs.microsoft.com/zh-cn/azure/storage/common/storage-concurrency?toc=%2fazure%2fstorage%2fblobs%2ftoc.json#overview)
* Content Source: [articles/storage/common/storage-concurrency.md](https://github.com/MicrosoftDocs/azure-docs.zh-cn/blob/live/articles/storage/common/storage-concurrency.md)
* Service: **storage**
* GitHub Login: @Jasontang501
* Microsoft Alias: **jasontang501**

**Comment by LisandroSu** [comment]
你好，@dusmart

感谢你的反馈。 

我们正在积极查看你的评论，并会很快地再次和你取得联系。 

深深的祝福， 
Microsoft DOCS International Team

**Comment by LisandroSu** [comment]
你好，@dusmart

感谢你的反馈。 

我们语言专家团队已评审并接受你的语言相关建议。我们已实施你的反馈，并将更新后的文章发布到 Docs 站点上的以下页面：[在 Microsoft Azure 存储中管理并发](https://docs.microsoft.com/zh-cn/azure/storage/common/storage-concurrency?toc=%2fazure%2fstorage%2fblobs%2ftoc.json#overview)。  

非常感谢你对我们的文章作出的贡献，欢迎继续提供宝贵的反馈。 

深深的祝福， 
Microsoft DOCS International Team
